### ISSUE TITLE
password policy control and detailed error message

### ISSUE THREAD

**Issue by thelliez** [ldapjs/node-ldapjs#186]
Hello,
I am using a ppolicy setup and I am trying to get more information out of a client.bind operation.

For example I get the same error msg for a wrong password, an expired account or a locked account:
"Error: InvalidCredentialsError: Invalid Credentials"

With ldappasswd, I can use the '-e ppolicy' option to return more detailed information.
"ldap_bind: Invalid credentials (49); Password expired"

Is there a way to get more info with ldapjs?

Thanks,
Thierry

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
