### ISSUE TITLE
Client should expose received controls for non-search actions

### ISSUE THREAD

**Issue by pfmooney** [ldapjs/node-ldapjs#192]
It appears that only client.search exposes received message controls via the EventEmitter during searchResult parsing.  Some other actions (see #186) would benefit from access to control information at the time of callback.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
