### ISSUE TITLE
Add support for RFC3673

### ISSUE THREAD

**Issue by pfmooney** [ldapjs/node-ldapjs#198]
Perhaps set some flag on the SearchRequest when '+' is observed in the attribute list?

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
