### ISSUE TITLE
Rename AbandonResponse

### ISSUE THREAD

**Issue by pfmooney** [ldapjs/node-ldapjs#210]
Per the rfc4511, there's no defined response to an AbandonRequest.
The existence of such an object is misleading.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
