### ISSUE TITLE
Returning multivalued attributes (such as member)?

### ISSUE THREAD

**Issue by tstiemerling** [ldapjs/node-ldapjs#233]
Noticed that when I query a group for the member attribute, the member attribute is returned as a string if there is only one member, and as an array if there is more than one member - meaning I have to handle this in my code. Wondering if this a common expected pattern? I am guessing that ldapjs doesnt know apriori whether it will get a single value or multiple values back.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
