### ISSUE TITLE
client should preserve better state around idleness

### ISSUE THREAD

**Issue by pfmooney** [ldapjs/node-ldapjs#282]
Whenever a client enters/leaves a state of idleness (when configured to track such events via idleTimeout), it would be useful to record a timestamp.  This would aid postmortem debugging.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
