### ISSUE TITLE
GSSAPI

### ISSUE THREAD

**Issue by zachaller** [ldapjs/node-ldapjs#29]
Just wondering if there is any plans to ever support GSSAPI for authentication

**Comment by mike-usa** [comment]
Curious if anyone is working on this.  Bump if not.  This seems advantageous to match `ldapsearch` util.

The issue, https://github.com/ldapjs/node-ldapjs/issues/85, points to a pull request, https://github.com/ldapjs/node-ldapjs/pull/473, which seems to be locked from comments.  Given the closed tag, I'm not sure if it was integrated into v2 -- I didn't think any SASL had been -- and there's a request for changes on the PR, making it seem it's still looming.

I haven't looked into the code, but if integrated a question remains whether SASL provides the ability to use GSSAPI, Kerberos, NTLM, etc or is limited in the PR's abstraction.  I could be mistaken, but I also thought the last time I read the docs on `createClient`, it didn't support GSSAPI or SASL and only basic auth.

**Comment by jsumners** [comment]
The PR was closed because it had been abandoned by the author. It was subsequently locked because people were not adding useful conversation around it. We welcome contributions to add desired functionality. But patience must be exercised as the maintainer team numbers 2, and we have other priorities.

**Comment by mike-usa** [comment]
> The PR was closed because it had been abandoned by the author. It was subsequently locked because people were not adding useful conversation around it. We welcome contributions to add desired functionality. But patience must be exercised as the maintainer team numbers 2, and we have other priorities.

Thank you for the reply and your logic sounds reasonable.  It's much easier for us consumers to be a requestor and express _wants_ than to be a capable developer and _fulfill_ them 😄  I admire this library and wish I could use it to replace a system call to `ldapsearch`.  In my case, GSSAPI is absolutely needed to interface with LDAP.

Regarding priorities, I am not sure how you are determining them, but I suspect it might have something to do with community-desire (interest) and ease-to-accomplish (time).  If we look at posts/comments over the years related to this issue, it seems the desire for GSSAPI/SASL started at least as long ago as 2011 and now (over 10 years later), comments are still trickling in from others (even on the PR mentioned in previous comment).  Perhaps the duration of this interest might elevate its priority?

In the meantime, I'll try to take a pass at the code, but I should mention this is outside my domain so I don't have any faith I could do it -- I wonder how many use this library that do.

**Comment by jsumners** [comment]
The only priority is what a contributor wants to work on. That is typically related to their own problems. Until someone who needs a feature contributes it, it will not be worked on.

**Comment by FROGGS** [comment]
PR #826 hopefully solves this issue. As I actually need this feature at work, I'm willing to spend more time on this if needed.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
