### ISSUE TITLE
How to use client.starttls()

### ISSUE THREAD

**Issue by lukelafountaine** [ldapjs/node-ldapjs#326]
I am having a little trouble figuring out how to use the client starttls() function. I am creating the client this way: 

```
client = ldap.createClient({
    url: config.ldap.url
});
```

The client is created correctly and upon calling the starttls function as 

```
client.starttls({}, function(err) {
    console.log('inside the starttls's callback');
});
```

However, the callback function never gets called. I get the error : `[TypeError: Object.keys called on non-object]`. In the Node.js TLS documentation it mentions that on connecting, if the certificate authority is left blank it will default to the system certificates, and I was assuming that this would act in the same way. If there were any thoughts on what is going wrong here, that would be great.

**Comment by pfmooney** [comment]
Please post the full stacktrace from the error.

**Comment by aneelaSaleem** [comment]
Please look at issue #307 
It might help you solve the problem

**Comment by aneelaSaleem** [comment]
Please look at issue #307
It might help you solve the problem

**Comment by pfmooney** [comment]
@aneelaSaleem It does not appear that this issue has anything to do with the difficulties you experienced in #307.  Please do not post references to tickets unless you know them to be related.

**Comment by lukelafountaine** [comment]
TypeError: Object.keys called on non-object
      at Function.keys (native)
      at wrapper (/usr/src/app/node_modules/ldapjs/node_modules/once/node_modules/wrappy/wrappy.js:27:14)
      at Client.starttls (/usr/src/app/node_modules/ldapjs/lib/client/client.js:880:14)
      at AuthenticationHelper.validateToken (/usr/src/app/helpers/authentication.js:97:12)
      at Server.AuthenticationCheck.checkAuth (/usr/src/app/middlewares/authenticationCheck.js:25:14)
      at next (/usr/src/app/node_modules/restify/lib/server.js:906:30)
      at f (/usr/src/app/node_modules/restify/node_modules/once/once.js:17:25)
      at b (domain.js:183:18)
      at Domain.run (domain.js:123:23)
      at Server._run (/usr/src/app/node_modules/restify/lib/server.js:959:7)
      at Server._handle (/usr/src/app/node_modules/restify/lib/server.js:719:14)
      at Server.onRequest (/usr/src/app/node_modules/restify/lib/server.js:326:14)
      at Server.emit (events.js:98:17)
      at HTTPParser.parser.onIncoming (http.js:2109:12)
      at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
      at CleartextStream.socket.ondata (http.js:1967:22)

**Comment by pfmooney** [comment]
Yeah, the non-optional controls parameter was an oversight in the implementation and needs to be fixed.

**Comment by shob0** [comment]
Please update the documentation as well that controls parameter is not optional.

**Comment by martinb3** [comment]
Just ran into this too -- it'd be nice to know controls aren't optional, when the examples omit it.

**Comment by woutrbe** [comment]
What are the "controls" supposed to be? The documentation just says `starttls(options, controls, callback)`.

But in the example there are no controls present, just options and callback: `client.starttls(opts, function(err, res) { });`

**Comment by kohleman** [comment]
Just ran into the same issue and this helped for me:
`
var controls = client.controls;
`

**Comment by siddjain** [comment]
@kohleman could you please tell what `protocol` and `ldapport` you are using?

**Comment by nihillno** [comment]
Hello all. Sorry for dredging up an old one, please feel free to tell me to sod off and create a new issue. ;o)

I'm trying to add StartTLS functionality to a project here, and am having difficulty getting the "minimal viable solution" to work, that is to say this little program:

```
var assert = require('assert');
var fs = require('fs');
const LDAP = require('ldapjs');

var opts = {
    ca: [fs.readFileSync('./ca.crt')],
    host: '192.168.86.200',
    reconnect: true,
    rejectUnauthorized: false // for self-signed
};

var client = LDAP.createClient({
    url: 'ldap://192.168.86.200:1389',
    tlsOptions: opts
});

var controls = client.controls;
var dn = 'cn=admin,dc=apic,dc=ibm,dc=com';
var password = 'adminpassword';

client.starttls(opts, controls, function(err, res) {
    assert.ifError(err);
    client.bind(dn, password, function (err) {
        assert.ifError(err);
    });
    console.log("StartTTLS connection established.")
});
```

...when pointed at an OpenLDAP server, results in the following:

```
bash-4.4$ node starttls_mvf.js
Caught exception: Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:617:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1544:19)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  path: undefined,
  host: '192.168.86.200',
  port: 1389,
  localAddress: undefined
}
bash-4.4$ 
```

What am I doing wrong?

**Comment by fengtan** [comment]
I also ran into this. As a workaround I have set the controls parameter to an empty array:

```
client.starttls(opts, [], function(err, res) { ... })
```

Which is basically what the other methods do when no controls are provided (and also what #651 offers).

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
