### ISSUE TITLE
client listener events documentations

### ISSUE THREAD

**Issue by iamtennislover** [ldapjs/node-ldapjs#340]
Hi,
I would like to know what are the events that I can listen on for client? Is there any documentation for this?

```
 var client = ldap.createClient({
            url: testurl
        });
client.on('error', function(err) {console.log(err)})
```

**Comment by dcolens** [comment]
I too would be interested to get some documentation about client events, there seems to be quite a lot:

- error
- destroy
- idle
- connectError
- setup
- resultError
- setupError
- socketTimeout
- end
- connect
- close
- timeout

while many are easy to guess, it would be great to get some documentation on the expected flows for these events :)

**Comment by teemuniiranen** [comment]
Definitely some documentation is needed. I am currently struggling with close for example. I have no idea how to test and raise this event but without handling it is crashing my app.

```
at Client._onClose (/data/app/node_modules/ldapjs/lib/client/client.js:1272:19)
at Object.onceWrapper (events.js:293:19)
at emitOne (events.js:96:13)
at Socket.emit (events.js:191:7)
at TCP._handle.close [as _onclose] (net.js:511:12)
```

**Comment by UziTech** [comment]
It might also be worth it to consolidate some of these events to make them more intuitive

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
