### ISSUE TITLE
Issue with guide example

### ISSUE THREAD

**Issue by jorgen-17** [ldapjs/node-ldapjs#347]
Hey, loving ldapjs so far, its definately been making learning and setting up ldap a lot more clearer than using slapd directly. Anyways just noticed there is a mistake in the examples located at http://ldapjs.org/guide.html. The examples look for a cn property in rdns[0]
i.e.

``` javascript
req.dn.rdns[0].cn
```

but they should be looking for it in rdns[0].attrs
i.e.

``` javascript
req.dn.rdns[0].attrs.cn
```

Other than this the documentation is a huge improvement over the slapd docs I've seen out there. Thanks for putting this together!

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
