### ISSUE TITLE
Is possible to write the binary field jpegPhoto, adding a ldap entry?

### ISSUE THREAD

**Issue by augcampos** [ldapjs/node-ldapjs#359]
I want to make a ldap add with a binary field how do I set it on the entry?

var entry = { uid: 'lalala', jpegPhoto: '{{ img content data in BASE64 }}'
ldap_client.add(dn, entry,function (err) {
...
});

this do not work :(

**Comment by augcampos** [comment]
I already try
```
var imgBase64 = '/9kljnfkjsdnf.......==';
.......
var userPhoto = new Buffer(imgBase64);
also try 
var userPhoto = new Buffer(imgBase64, 'base64');
also try 
var userPhoto = new Buffer(imgBase64, 'binary');
.....
var entry = { uid: 'lalala', jpegPhoto: userPhoto };
ldap_client.add(dn, entry,function (err) {
...
});
```

all did not work :(

PS: What I need is to add a new entry on ldap with the jpegPhoto filled with a image-src 
like  `<img ng-src="{{'data:image/png;base64,'+main.user.jpegPhoto}}">`    from a LDAP jpegPhoto property

**Comment by feraudet** [comment]
@augcampos Have you found any solution ?

**Comment by feraudet** [comment]
@augcampos  `var userPhoto = new Buffer(imgBase64, 'base64');` would work fine with this PR: https://github.com/mcavage/node-ldapjs/pull/383

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
