### ISSUE TITLE
It throws exception when Ldap Server returns 9 error code (LDAP_PARTIAL_RESULTS)

### ISSUE THREAD

**Issue by gaupoit** [ldapjs/node-ldapjs#366]
Our LDAP server returns error code is 9 and I looked at the codebase. I don't know why it is not in codes.js and it will cause an error here

`module.exports.getError = function (res) {`
`assert.ok(res instanceof LDAPResult, 'res (LDAPResult) required');`

`var errObj = ERRORS[res.status];`
==> **`var E = module.exports[errObj.err];`**
`return new E(res.errorMessage || errObj.message,`
`res.matchedDN || null,`
`module.exports.getError);`
`};`

because errObj is undefined. Should we add `LDAP_PARTIAL_RESULTS: 9` in codes.js?

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
