### ISSUE TITLE
exop sample (whois) not working

### ISSUE THREAD

**Issue by ptusch** [ldapjs/node-ldapjs#370]
Hi,

the `exop` sample on ldapjs.org does not work with OpenLDAP (2.4.40).
It seems to be that ldapjs doesn't fully respect [RFC 4532](https://tools.ietf.org/html/rfc4532).
**Point 2.1. of the RFC**:

```
[...] The whoami request is an ExtendedRequest with a requestName field
containing the whoamiOID OID and an absent requestValue field. [...]
```

Here's my output for exop with the OID `1.3.6.1.4.1.4203.1.11.3`

```
ProtocolError: no request data expected
```

Removing [L589](https://github.com/mcavage/node-ldapjs/blob/master/lib/client/client.js#L589) of the client.js, results is a nice WhoIs output.

This is my sample to call the exop with the who is OID:

```
function whoami() {

  return new Promise((resolve, reject) => {

    client.exop('1.3.6.1.4.1.4203.1.11.3', (err, value, res) => {

      if (!!err) {
        return reject(err);
      }
      return resolve(value);
    });
  });
}
```

The problem is that `requestValue` is encoded into Ber and then send to LDAP.

I'm not sure how to solve the issue without much trouble. I don't know all OID and their RFC so I assume having a list of OID which need to be treated special is needed.
Simply removing the key `requestValue` when the content is `null` sounds like trouble.

Any thoughts on this and how you'd like it to be solved? I'd totally PR you with a fix.

Some additional data about my versions:
node: 4.3.3
ldapjs: 1.0.0

**Comment by jsumners** [comment]
This issue should be resolved in `ldapjs@2.0.0-pre.3`. Please give it a try if you are still affected.
