### ISSUE TITLE
Wrong event names after uglify-ing the code

### ISSUE THREAD

**Issue by strebl** [ldapjs/node-ldapjs#406]
I have an issue with the ldap client.

In one of my build step, the javascript code gets uglyfied. In that step, functions getting renamed etc. Normally that's not a problem, but because the event name in the client is generated off of the [message name](https://github.com/mcavage/node-ldapjs/blob/master/lib/client/client.js#L1409), a wrong event will be raised.

I think instead of getting the name from `msg.constructor.name`, getting it with `msg.type` would fix the problem.

I'll create a PR with my solution.

**Comment by strebl** [comment]
🔔 Ping @pfmooney 😊

**Comment by grogi** [comment]
https://github.com/joyent/node-ldapjs/pull/492

**Comment by jsumners** [comment]
I am unclear why one would even need to minify/uglify this library. The intention of this library is to be used in a Node.js environment. Minification does nothing in such an environment.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
