### ISSUE TITLE
Boolean attributes aren't retrieved when I pull all attributes from LDAP for 1 user

### ISSUE THREAD

**Issue by YYAK** [ldapjs/node-ldapjs#430]
Boolean attributes aren't retrieved when I pull all attributes from LDAP for 1 user. Is there a bug that prevent having boolean properties? I am retrieving user data from Windows active directory.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
