### ISSUE TITLE
Bitwise filtering is not enabled -- (UserAccountControl:1.2.840.113556.1.4.803:=2)

### ISSUE THREAD

**Issue by fuka-michal** [ldapjs/node-ldapjs#439]
Im not able to filter with bitwise operators.

Filter like this: (UserAccountControl:1.2.840.113556.1.4.803:=2)

Please see https://support.microsoft.com/en-us/help/269181/how-to-query-active-directory-by-using-a-bitwise-filter

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
