### ISSUE TITLE
ldapseach operational attributes 

### ISSUE THREAD

**Issue by projadmin** [ldapjs/node-ldapjs#449]
Hi,
How to search operational attributes like :  createtimestamp, modifytimestamp, pwdchangedtime
using ldapjs npm. Usually we use '+' to search these attributes, but somehow its not working at my end.
Thanks in advanced.

**Comment by Snowmanko** [comment]
I am also interested. Did you discovered how to fetch operational attributes ?

**Comment by Machecek** [comment]
Hi guys, i have just bumped into this issue

@projadmin @Snowmanko you can do it this way:
opts = {
    scope: 'sub',
    attributes: ['*','+']
};

See the "+" sign in attributes option

**Comment by Taggotty** [comment]
maybe this could be added to the docs?

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
