### ISSUE TITLE
Client timeout doesn't work, searches hang forever if remote server goes down

### ISSUE THREAD

**Issue by glennschmidt** [ldapjs/node-ldapjs#463]
To reproduce:

1. Create a client, setting the timeout option (eg. 4 seconds):
```JS
ldap.createClient({url: 'ldap://directory:389', timeout: 4000, connectTimeout: 4000});
````
2. `starttls` then `bind`
3. `search` -> The search is successful
4. Shut down the server (slapd), then start it up again
5. Issue another `search` -> The callback is never called, the search never succeeds or fails, and the client doesn't emit any 'error' event

Ideally, ldapjs should notice that its TCP connection has gone down (due to the server restarting), and would automatically reconnect when the next query is issued.

But at minimum, it should notice that it hasn't received a response to the search within the 4-second timeout window, and emit an error so that I can reconnect manually.

**Comment by rdubigny** [comment]
Concerning the issue of the never resolving promise, I use the workaround of wrapping the `res` EventEmitter in a bluebird promise:
```js
const resultPromise = new Promise((resolve, reject) => {
  const entries = [];
  res
  .on('searchEntry', ({object: entry }) => {
    entries.push(entry);
  })
  .on('error', err )> {
    reject(err);
  })
  .on('end', ({status}) => {
    if (status !== 0) {
      return reject(new Error(`LDAP error: ${status});
    }
    resolve(entries);
  });
}).timeout(4 * 1000, 'LDAP search timed out');
```

This solution is not clean as we don't know the state of the TCP connection at this point but it works.

We found out that a concurrency issue (solved with https://github.com/joyent/node-ldapjs/pull/424) cause the EventEmitter to hang forever without emitting any error. The `timeout` & `connectTimeout` did not seems to work neither.

Hope it helps.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
