### ISSUE TITLE
Can we get support for Extensible Matching? 

### ISSUE THREAD

**Issue by PsychoData** [ldapjs/node-ldapjs#494]
Extensible Matching, at least [LDAP_MATCHING_RULE_IN_CHAIN / 1.2.840.113556.1.4.1941](https://ldapwiki.com/wiki/1.2.840.113556.1.4.1941) would be great

https://ldapwiki.com/wiki/ExtensibleMatch

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
