### ISSUE TITLE
Bind requests & concurrency

### ISSUE THREAD

**Issue by lneveu** [ldapjs/node-ldapjs#506]
Hi,

I'm using Verdaccio (a private npm proxy registry) with LDAP authentication (OpenLDAP 2.4.47) via the [verdaccio-ldap](https://github.com/Alexandre-io/verdaccio-ldap) plugin (that uses [ldapauth-fork](https://github.com/vesse/node-ldapauth-fork) and node-ldapjs libs).
I'm facing issues with authentication and, after digging into it, I found the "problem".

According to LDAP RFC (LDAPv3 RFC 4511 - section 4.2.1 https://www.ietf.org/rfc/rfc4511.txt), multiple "Bind Requests" should not be sent concurrently and must fullfil some requirements (see rfc).
Unfortunatly, I don't think there is a mecanism either in ldapauth-fork or node-ldapjs to manage this and ensure that bind requests are performing synchronously (or wait for response to a bind before performing another).

Does each clients that using node-ldapjs (in my case ldapauth-fork) have to manage that or do you plan to do it internally?

**Comment by jsumners** [comment]
I do not know if this has ever been a consideration. If you'd like to submit a PR to implement this, I would certainly be willing to consider it.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
