### ISSUE TITLE
Array of changes is not accepted in client.Modify

### ISSUE THREAD

**Issue by willmcenaney** [ldapjs/node-ldapjs#514]
Array of changes is not accepted in client.Modify
Documentation states "Note that you can pass in a single Change or an array of Change objects." and code is present to assert is change instead of passing to the code further down that copes with an array of changes.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
