### ISSUE TITLE
Split client and server

### ISSUE THREAD

**Issue by tastypackets** [ldapjs/node-ldapjs#526]
In my experience often times the server is never used, since in most cases we want to use this lib to connect to an existing LDAP server.

Would it make sense to split this lib into 2 packages?

For example:
`@ldapjs/client`
`@ldapjs/server`

General question / discussion. 😄

**Comment by jsumners** [comment]
It's possible. I will say I use the server part extensively in https://github.com/jsumners/node-activedirectory for unit testing. But for the moment I am much more concerned with getting a new `ldapjs` module published.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
