### ISSUE TITLE
About the state of maintenance

### ISSUE THREAD

**Issue by jsumners** [ldapjs/node-ldapjs#570]
This issue is to give clear notice about the current state of maintenance of this module.

In July of 2019 [I offered](https://github.com/nodejs/package-maintenance/issues/221#issuecomment-511462330) to pick up the maintenance of this project from Joyent. Subsequently, the repo was transferred to the ldapjs org and I was granted this role. When I offered to take over I was upfront about not being able to dedicate much more time than was already being dedicated to this module, but I would be able to dedicate at least something. That has not changed, but that promise is in an obscure place so I am bring it forth here directly.

My time for this project is _very_ limited. The only time I have to work on it is on weekends or vacation days. And then only when I don't have other things going on and have the will to work. As you can probably imagine, this will make for slow going on the project.

My plan for a next release:

1. "Clean up" the code base as much as possible without changing the outward functionality. By "clean up" I mean move shared code into independent testable modules (see the new modules being developed in the organization) and generally making it easier for people to get into the code and contribute to it.

2. Resolve open issues. I don't want to outright close issues for no reason, but if the author has abandoned the issue by not responding when prompted, that is likely to happen.

3. Resolve open PRs. I _really_ don't want to just close these without due consideration.

There's a lot of work in all three of those things. If you wait on me and @UziTech to do it all ourselves then your wait will continue to be a very long one. If you have an issue, then dig into the code, figure out where it lies, and submit a PR that either 1) outright fixes it or 2) introduces a failing test in the test suite that covers it. Do not expect issues without accompanying PRs to get resolved quickly.

You can also help by working on current issues or resolving current PRs. In the case of a current PR, it would be ideal if you can branch off of that person's branch so they get credit for their work. But since all PRs _must_ target the `next` branch before they will be considered for merging, that may not be feasible. Do your best.

After the next release, _whenever_ that happens, I plan to expand the list of people who can directly commit to this repository. Until that time, I want to be able to coordinate efforts without conflicts.

**Comment by DavidIHunt** [comment]
If you do nothing else on this project, please PLEASE merge this...
https://github.com/ldapjs/node-ldapjs/pull/433

It's been 2 years!

The bug it fixes is making this module awful to use. Imagine trying to call a function of a library which can asynchronously throw an error that you can't catch and which will crash your process.

**Comment by hongkongkiwi** [comment]
Thank you thank you thank you!

How can we help? I'm a bit overwhelmed and confused with all the pull requests here and things. Is there a way we can contribute ?

**Comment by jsumners** [comment]
@hongkongkiwi just start with one PR or issue that attracts you. This is exploratory for all of us.

**Comment by jsumners** [comment]
All of my statements in this issue still apply. But v2.0.0 has been released, so I am closing and locking this.
