### ISSUE TITLE
Error: Expired certificate causes untrappable error / breaks NodeJS.  (Fix included)

### ISSUE THREAD

**Issue by tfrancois** [ldapjs/node-ldapjs#589]
Using NodeJS 10.13 and LDAPjs 2.0.0-pre.5, when connecting to an LDAP server with a TLS SSL certificate that has expired an error occurs that cannot be handled or trapped via catch error handling in NodeJS.  The fatal error that occurs is as follows:
```
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at TLSSocket._finishInit (_tls_wrap.js:633:8)
Emitted 'error' event at:
    at Backoff.<anonymous> (...\node_modules\ldapjs\lib\client\client.js:1020:12)
    at Backoff.emit (events.js:198:13)
    at Backoff.EventEmitter.emit (domain.js:448:20)
    at Backoff.backoff (...\node_modules\backoff\lib\backoff.js:41:14)
    at ...\node_modules\ldapjs\lib\client\client.js:1002:15
    at f (...\node_modules\once\once.js:25:25)
    at TLSSocket.onResult (...\node_modules\ldapjs\lib\client\client.js:804:7)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
```
I was able to solve the issue by adding the following to **client.js** starting at lines 1006:
```
retry.on('fail', function (err) {
    if (self.destroyed) {
      // Silence any connect/setup errors if destroyed
      return
    }
    self.log.debug('failed to connect after %d attempts', failAfter)
    // Communicate the last-encountered error
    if (err instanceof ConnectionError) {
      self.emit('connectTimeout', err)
    } else if (err.code === 'ECONNREFUSED') {
      self.emit('connectRefused', err)
    } else if (err.code === 'CERT_HAS_EXPIRED' || err.code === 'UNABLE_TO_VERIFY_LEAF_SIGNATURE') {  // <-- THIS FIXED EXPIRED CERT ERROR
      self.emit('connectError', err)
    } else {
      self.emit('error', err)
    }
  })
```
The specific change that was added was:
```
} else if (err.code === 'CERT_HAS_EXPIRED'  || err.code === 'UNABLE_TO_VERIFY_LEAF_SIGNATURE') {
      self.emit('connectError', err)
```
Any variation of the above did not work for me, as this change worked perfectly.  Please merge this fix to future updates.  (I did not create a pull request but wanted to provide an important fix for the benefit of all users of this important library).

**Comment by jsumners** [comment]
Why not submit a PR?

**Comment by tfrancois** [comment]
Modified the code above to account for yet another certificate error I came across.  This new particular error has to do with the (valid) CA certificate chain not being able to be properly verified.  I think it has to do with the cert being SHA-256 based rather than SHA-1.  Either way, the cert is valid but ldapjs didn't accept it and crashed Node.  Again adding the additional error checks allowed the error to be handled much more smoothly and without a fatal error.  Please include in next build.

**Comment by jonekdahl** [comment]
I took the liberty of creating a PR with the suggested fix.

**Comment by UziTech** [comment]
What is the benefit of emitting a `connectError` instead of emitting an `error`?

**Comment by jonekdahl** [comment]
@UziTech I'm not sure, could it be that it avoids an [error event](https://nodejs.org/api/events.html#events_error_events)?

**Comment by UziTech** [comment]
But wouldn't you want that to be an `error` event so it would throw if it isn't handled?

**Comment by jonekdahl** [comment]
I think I see what you're saying. Could this error be handled/trapped by adding a listener for the error event?

```javascript
client.on('error', (err) => {
  // handle error here
});
```

**Comment by jonekdahl** [comment]
@tfrancois In case you haven't followed the discussion in the PR, the error is trappable by adding a listener for the `error` event on the client object, see exemple in https://github.com/ldapjs/node-ldapjs/pull/595#issuecomment-582441969.

**Comment by tfrancois** [comment]
Thank you all for the feedback and assistance.  I can confirm this resolves this issue.  Interesting fact: I was listening for ``connectError`` which explains why I was not trapping the certificate expiration error, rather than the generic ``error``.  Listening for both types should resolve most if not all errors that may occur during client creation.
