### ISSUE TITLE
Double emission of error in failed bind

### ISSUE THREAD

**Issue by jsumners** [ldapjs/node-ldapjs#592]
https://github.com/ldapjs/node-ldapjs/blob/8384a4736ff03bc6a09da5ee0e12d69eae02d277/lib/client/client.js#L157-L159

When the client fails to bind, e.g. due to invalid credentials, it generates the same error event twice. We should figure out a way to emit this only once.

**Comment by UziTech** [comment]
That's what I was talking about in https://github.com/ldapjs/node-ldapjs/pull/574#issuecomment-541458835 . I don't know of any other packages that us event emitters and callbacks. I'm thinking the easiest way to solve it would be to eliminate callbacks and just use the event emitter.

**Comment by jsumners** [comment]
Yeah, I thought I remembered a discussion. I agree at least for the connection events. But in this specific case, I think the ultimate solution is to remove the automatic bind on client creation. But I'd rather have that in a v3 release because it is a _very_ major change.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
