### ISSUE TITLE
Fetch only one page results

### ISSUE THREAD

**Issue by Jose96GIT** [ldapjs/node-ldapjs#601]
Hi all, I'm having a problem with fetching directly a page of my results. For example, having a paging of 100 results per page with a total of 200 results, I'll have 2 pages. Is it possible to fetch directly the results of the second page without having also the results of the page?

**Comment by jsumners** [comment]
No. That's not how LDAP works. However, there is a server extension that may help. See the PR released under `ldapjs@next` -- https://github.com/ldapjs/node-ldapjs/pull/553

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
