### ISSUE TITLE
Fork asn1 package

### ISSUE THREAD

**Issue by jsumners** [ldapjs/node-ldapjs#616]
We shouldn't need to depend on an unmaintained asn1 package. Currently, we depend upon https://github.com/joyent/node-asn1. At the time of this writing, the most recent commits going back for a year are all related to internal build tools for Joyent's internal usage of the module. The module has several issues open and a few PRs that are basically ignored. We should fork this library, update it, and publish it under the `@ldapjs` namespace.

Or, and this is probably a better plan, we work with @panva to add BER encoding and decoding to https://github.com/panva/asn1.js

**Comment by UziTech** [comment]
If @panva is willing to add it, I think that would be the better option as well.

**Comment by panva** [comment]
He is not. I intend to keep the fork inline with the original package only without the browser polyfills

**Comment by UziTech** [comment]
Thanks for responding @panva. :+1:

Well, I guess creating a package with the `@ldapjs` namespace it is.

**Comment by jsumners** [comment]
Fork repo created -- https://github.com/ldapjs/asn1

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
