### ISSUE TITLE
LDAP search not working but works from ldapquery command line

### ISSUE THREAD

**Issue by suityou01** [ldapjs/node-ldapjs#624]
The following query works fine from command line 

```
ldapsearch -b "DC=corp,DC=example,DC=com" -H ldap://192.168.1.102 -D "administrator@corp.example.com" -w ThisIsMyAdminPassword! -s sub "(objectclass=user)"
```

I can bind ok but when I run the search it doesn't return anything.

I am trying to do the same as above but using node-ldapjs like this

```js
const opts = {
                filter: '(objectclass=user)',
                scope: 'sub',
                attributes: ['dn', 'sn', 'cn']
            };
            const retVal=[];
            this.ldap_client.search('dc=corp,dc=example,dc=com', opts, function(err, res) {
                res.on('searchEntry', function(entry) {
                    retVal.push(entry);
                    console.log('entry: ' + JSON.stringify(entry.object));
                });
                res.on('searchReference', function(referral) {
                    retVal.push(referral);
                    console.log('referral: ' + referral.uris.join());
                });
                res.on('error', function(err) {
                    retVal.push(err);
                    console.error('error: ' + err.message);
                });
                res.on('end', function(result) {
                    retVal.push(result);
                    console.log('status: ' + result.status);
                });
            
            });
            return retVal;
``` 
Retval returns and empty array []

Any ideas?

**Comment by jsumners** [comment]
You are returning `retVal` before the search is completed. You should be getting `retVal` via a callback.

**Comment by thebpmgroup** [comment]
Yet the console logs don't fire either

**Comment by jsumners** [comment]
Can you replicate it with our integration tests?

**Comment by suityou01** [comment]
Good point on the retval. I think I was looking at the console logs that weren't firing anything to the console but you weren't to know this.

I changed the code to return in the events so it now reads

```
const opts = {
               (sAMAccountName=${userName}))`,*/
                filter: '(objectclass=user)',
                scope: 'sub',
                attributes: ['dn', 'sn', 'cn']
            };
            
            this.ldap_client.search('dc=corp,dc=example,dc=com', opts, function(err, res) {
                res.on('searchEntry', function(entry) {
                    return entry;
                    console.log('entry: ' + JSON.stringify(entry.object));
                });
                res.on('searchReference', function(referral) {
                    return referral;
                    console.log('referral: ' + referral.uris.join());
                });
                res.on('error', function(err) {
                    return err;
                    console.error('error: ' + err.message);
                });
                res.on('end', function(result) {
                    return result;
                    console.log('status: ' + result.status);
                });
            
            });
```

It does not return anything so it's like none of the events fire at all. Is this possible? Is it correct behaviour?

I can try to reproduce with your integration tests, which test should I run? How would I go about that?

**Comment by suityou01** [comment]
Never mind I ran all the tests using npm

```
Suites:   54 passed, 54 of 54 completed
Asserts:  2678 passed, of 2678
Time:     7s
```

**Comment by jsumners** [comment]
You're returning from the event handlers before issuing any log statements; your log statements are unreachable.

I do not see how you are using this code and expecting it to work. As it is, it's an out-of-context snippet of code that has the potential to work or not.

It seems to me, based upon the snippets you have provide, that you need to learn how to work with event emitters. That is outside of the scope of this issue tracker. A quick search (https://duckduckgo.com/?q=nodejs+event+emitter+tutorial) yields this decent looking article -- https://www.digitalocean.com/community/tutorials/using-event-emitters-in-node-js

I'm closing this as it seems this is not a problem with the library. If you encounter an error with the library, please open an issue clearly detailing that error.

**Comment by thebpmgroup** [comment]
I think maybe you are being a little capricious. It's been a long day. The concept of callbacks, no matter whether you call them event emitters or publisher subscribers is not lost on me, it's been a long day. 

Yes it's a code snippet, but it's such a basic one I'm sure man of your clear expertise could stand to give better advice than your snippy short tempered version above. Don't assume anything about me from a code snippet. Don't patronise. It's unnecessary and unhelpful.

Before I said the console logs were not firing. This was before moving the return statements. This is enough for you to understand that based on the successful bind, with those parameters I was getting nothing back.

You have ignored my question on whether this is normal behaviour or not. 

Then, as you rightly point out, I moved the return statements to somewhere crazy. As I said it's been a long day and it's late here. But the point that none of the events are firing is proved.

Is this normal?
Would a search really not fire any event, even if it found nothing? I note you don't have a test case for this scenario, and it's not in the documents, so I cannot infer this easily. Hence the question.

How should one write a successful query to LDAP using your library? Could the documentation be better?

How about dialling it down a little and being more helpful?
