### ISSUE TITLE
STARTTLS support for the Server API

### ISSUE THREAD

**Issue by christiaangoossens** [ldapjs/node-ldapjs#663]
Just an investigation into the possibilities of adding this: currently the server supports LDAP and LDAPS, through the default `tls.createServer()` method. It is however recommended to use STARTTLS instead of LDAPS, which is not actually an official protocol anymore, afaik.

It's not possible to implement a TLS upgrade in the `exop` handler as far as I know, could it be done in the lib itself? Would it be much work? The implementation in the client looks rather simple.

Hoping to hear from someone more knowledgeable on this code about this. Thank you!

_For reference, it would use https://nodejs.org/api/tls.html#tls_new_tls_tlssocket_socket_options, `new tls.TLSSocket`, just not sure how to obtain a socket or to register the listeners here._

**Comment by jsumners** [comment]
You probably have more knowledge of this than anyone currently maintaining this library. We'd welcome your research into the matter, and a pull request if you are able.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
