### ISSUE TITLE
Server Pool support

### ISSUE THREAD

**Issue by thernstig** [ldapjs/node-ldapjs#668]
The Python lib 'ldap3' supports something called a Server Pool: https://ldap3.readthedocs.io/en/latest/server.html#server-pool

It would be nice of ldapjs also supported this.

**Comment by jsumners** [comment]
If you'd like to send a pull request to add this feature, we would certainly consider it. Remember to add unit tests.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
