### ISSUE TITLE
Request: client.ping() convenience method

### ISSUE THREAD

**Issue by mcandre** [ldapjs/node-ldapjs#675]
Please provide a `ping()` convenience method for healthchecks to analyze whether the client object has a good connection to the LDAP server.

For example, submit a search query.

This represents a common operation that users shouldn't have to dig into low level details to figure out.

**Comment by UziTech** [comment]
PRs are always welcome. 😁

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
