### ISSUE TITLE
change ldapjs.org dns record

### ISSUE THREAD

**Issue by UziTech** [ldapjs/node-ldapjs#679]
The `ldapjs.org` dns needs to be updated. I updated the gh-pages and got this error by email:

```
The custom domain for your GitHub Pages site is pointed at an outdated IP address.
You must update your site's DNS records if you'd like it to be available via your custom domain.
```

It looks like the dns should point to

```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

@jsumners do you know who controls the domain name?

**Comment by jsumners** [comment]
Ugh. That's a thing we never got around to dealing with. Technically Joyent still owns all of that. I'll reach out to people and see if we can get it moved somewhere else. But it may be that we just need to kill of the domain.

**Comment by UziTech** [comment]
We could just use `ldapjs.github.io` by moving the gh-pages branch to the repo `ldapjs/ldapjs.github.io`

**Comment by jsumners** [comment]
Yeah, that sounds like a good solution.

**Comment by UziTech** [comment]
I created the repo and set up https://ldapjs.github.io/ I think it would be better if we could work something out with Joyent to keep the domain, but if not we will just need to point everything to the new domain.

**Comment by jsumners** [comment]
@melloc do you have any opinions about managing DNS for `ldapjs.org`?

Personally, I'm of the opinion that we should just let the domain die. Maybe add a year to it and set it up as a 301 to `ldapjs.github.io`. It'll be far easier to maintain as an organization going forward. If we were to try to keep `ldapjs.org` then someone would have to keep it paid for, and the org will always be wondering if that person will keep up with it or just disappear and be stuck without the domain.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
