### ISSUE TITLE
how get get constructed attributes in search?

### ISSUE THREAD

**Issue by preussmann** [ldapjs/node-ldapjs#699]
I'm trying to find out, how to get a constructed attribute in search. f.e.: msDS-PSOApplied

**Comment by jsumners** [comment]
I don't know what you're asking. What is a "constructed attribute"?

**Comment by preussmann** [comment]
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/a3aff238-5f0e-4eec-8598-0a59c30ecd56
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-ada2/a182b5e8-8141-43e4-9c17-67fade1984a7

**Comment by jsumners** [comment]
Are they part of the LDAP specification?

**Comment by preussmann** [comment]
yes

**Comment by jsumners** [comment]
According to https://web.archive.org/web/20200925170437/https://ldapwiki.com/wiki/Constructed%20Attribute they would be considered "Virtual Attributes" in a standard LDAP server. Regardless, it sounds like a server implementation detail. This library parses the attributes returned by the search query. If the server isn't returning such attributes in the result, how can the library read them?

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
