### ISSUE TITLE
Paged events still not firing as expected

### ISSUE THREAD

**Issue by GGGav** [ldapjs/node-ldapjs#712]
Folks,
I am having exactly the issue described in #385.
I'm running a node JS (v15.11.0) app on a linux box trying to pull user accounts from Microsoft AD.  There are 1100 user account present.  I get the first 100 as separate 'searchEntry' events.  I then get a 'page' event with a callback.  I call the callback, as per the 'terryxsq' comment in issue 385, but there are no further results.
The next event is 'unbind'.

The OP for #385 also said that calling the callback didn't work for them yet the next comment closes the call suggesting it has been resolved.

My code is as per the examples on the web site.
Has anybody ever got this to work?   Can someone post some working code?

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
