### ISSUE TITLE
Is there a way to retrieve a user's management chain without performing recursive calls to search

### ISSUE THREAD

**Issue by donraikes** [ldapjs/node-ldapjs#725]
I need to be able to quickly locate the first vice president above a given user and return that VP's name and email address.
Is there any query filter that can do this kind of query?
I saw something about using directreports to get all a users managers, but couldn't find a good example of the syntax.

Can ldapjs handle the directreports filter?

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
