### ISSUE TITLE
How to get messageId after client.search

### ISSUE THREAD

**Issue by zyf0330** [ldapjs/node-ldapjs#728]
MS AD support Change Nofitication https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/f14f3610-ee22-4d07-8a24-1bf1466cba5f , and abandon op needs messageID is allowed before receiving search response.
I find that messageID is created when create searchRequest instance, but don't know how to take it. Maybe it shoule be returned by Client#search method.

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by zyf0330** [comment]
I will try

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
