### ISSUE TITLE
ExtendedDN 

### ISSUE THREAD

**Issue by domsen123** [ldapjs/node-ldapjs#735]
Is it possible to set the ExtendedDN Attribute in search api?

https://docs.microsoft.com/de-de/dotnet/api/system.directoryservices.extendeddn?view=net-5.0

**Comment by UziTech** [comment]
I don't think so (I've never used ExtendedDN). Is there something extra the client would have to send along with the filter?

PRs are always welcome 😁👍

**Comment by jsumners** [comment]
It would be better to research how the attribute is implemented in terms of LDAP attributes instead of the .net sdk.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
