### ISSUE TITLE
size limit causing problems

### ISSUE THREAD

**Issue by donraikes** [ldapjs/node-ldapjs#737]
Hello,
I am attempting to perform an ldap search using the following options:
    var opts {
            scope: "sub",
    		        filter: `(|(displayName=*${user}*)(mail=*${user}*))`,
    				        attributes: ["displayName", "mail", "title", "manager","orclcorpcostcenter","ou"],
    								sizeLimit: 1000
    								    };

All works fine until the number of ldap responses exceeds the size limit.

For example if ${user} = "john"  I don't know how many results that returns, but with size limit 1000, what I get back is an empty json object.

If I use any search criteria that returns less than the size limit set, I get all the data I want.

I am running an express.js server serving this data in a rest api.

**Comment by UziTech** [comment]
Are you subscribed to the `error` event on the server or client? Do you get any errors?

It would be a lot easier for us to debug if you could share you code setting up the ldapjs client or server.

**Comment by donraikes** [comment]
The express server is subscribed to the client error events (see server.txt) for my express server code.
I am now getting a different error which is causing my express server to fail any time an end point is accessed.  It looks like there is some kind of connection reset happening (see server.log) for the errors.
[server.txt](https://github.com/ldapjs/node-ldapjs/files/6618550/server.txt)f
[server.log](https://github.com/ldapjs/node-ldapjs/files/6618555/server.log)

**Comment by UziTech** [comment]
this seems like an issue with your server. Are there any errors on your server when `sizeLimit` is sent?

It could also be that `JSON.stringify` is failing in your `doSearch` function and you aren't catching the error. You could try logging `entry.object` on `searchEntry` to see what it is returning.

**Comment by donraikes** [comment]
Ok so I added a console.log(entry.object) and all seems to be working until I run into a timeout exceeded error.

I guess I need to set the timelimit in my search options.

**Comment by donraikes** [comment]
I modified my ldap.createClient to include timeout:5000 and connectTimeout:1000.
Now when I run my test query, I am getting the size limit exceeded error.

Is there a way to retrieve just the first 100 results without throwing an error?

**Comment by jsumners** [comment]
We have tests specifically around size limits -- https://github.com/ldapjs/node-ldapjs/blob/3430f05d91bc152b18febe1f04665c8aea0faf11/test/client.test.js#L745-L774

If they are not sufficient, feel free to add some to our integration tests -- https://github.com/ldapjs/node-ldapjs/blob/3430f05d91bc152b18febe1f04665c8aea0faf11/test-integration/client/issues.test.js

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
