### ISSUE TITLE
client.modifyDN fails 

### ISSUE THREAD

**Issue by Genp0** [ldapjs/node-ldapjs#740]
client.modifyDN fails without any error message when dn is more than 112 characters

**Comment by UziTech** [comment]
Can you share a script that reproduces this behavior?

**Comment by Genp0** [comment]
`  try {
    const client = ldap.createClient({
      url: 'ldap://172.26.4.234',
      tlsOptions: { rejectUnauthorized: false },
      bindDN: 'junpengl@lstest.com',
      bindCredentials: 'Aa123456',
    });
    client.modifyDN(
      'CN=周军,OU=谷科技有限公司,OU=朗科技集股份有限公司,OU=test,DC=ltest,DC=com',
      'CN=周军,OU=项目管理部,OU=南区项目实施中心,OU=谷科技有限公司,OU=朗科技集股份有限公司,OU=test,DC=ltest,DC=com',

      (err, res) => {
        if (err) {
          console.error(err);
        } else {
          console.log(res);
        }
      }
    );

`
and response is
`{
  messageID: 2,
  protocolOp: 109,
  controls: [],
  log: { child: [Function (anonymous)] }}`

thx

**Comment by UziTech** [comment]
try catching the error with `client.on('error', (err) => { console.error(err); });

**Comment by Genp0** [comment]
trying with client.on('error', (err) => { console.error(err); }),there is still no error message.

**Comment by jsumners** [comment]
Seems related to #480? https://github.com/ldapjs/node-ldapjs/blob/3430f05d91bc152b18febe1f04665c8aea0faf11/test-integration/client/issues.test.js#L12-L41

**Comment by Genp0** [comment]
modifying the DN is no problem, no matter how long the string is.
However, if the string containing OU is modified too long, it will be invalid.
<img width="804" alt="Snipaste_2021-07-13_10-50-37" src="https://user-images.githubusercontent.com/24952543/125382409-32ca1180-e3c8-11eb-9dcc-3d21ff37de44.png">

**Comment by JohnTJohnston** [comment]
Ran into this problem and developed a solution that appears to work.  Please review modified lib/moddn_request.js:prototype._toBer to:

`ModifyDNRequest.prototype._toBer = function (ber) {
  // assert.ok(ber);

  ber.writeString(this.entry.toString())
  ber.writeString(this.newRdn.toString())
  ber.writeBoolean(this.deleteOldRdn)
  if (this.newSuperior) {
    const s = this.newSuperior.toString()
    const len = Buffer.byteLength(s)

    ber.writeByte(0x80) // MODIFY_DN_REQUEST_NEW_SUPERIOR_TAG
    ber.writeLength(len) // *************ADDED THIS************
//  ber.writeByte(len)   // *************REMOVED THIS**********
    ber._ensure(len)
    ber._buf.write(s, ber._offset)
    ber._offset += len
  }

  return ber
}
`

The above is a propper fix for #97

**Comment by JohnTJohnston** [comment]
I think that:

`const s = this.newSuperior.toString()
const len = Buffer.byteLength(s)
ber.writeByte(0x80) // MODIFY_DN_REQUEST_NEW_SUPERIOR_TAG
ber.writeLength(len) // *************ADDED THIS************`

Can be replaced with:

`ber.writeString(this.newSuperior.toString(), 0x80)`

Do you think that there are other ldapjs areas where writeByte is incorrectly used?

**Comment by UziTech** [comment]
@JohnTJohnston if you can create a PR with that change we could get this fixed
