### ISSUE TITLE
 event names for searchEntry && searchReference are 'broken'

### ISSUE THREAD

**Issue by hillar** [ldapjs/node-ldapjs#765]
https://github.com/ldapjs/node-ldapjs/blob/b64ed9fd63588667ddda4a638f0eb4e36a43d738/lib/client/client.js#L1208

if `constructor.name` is not same as `instanceof` events will get 'wrong name'

**Comment by roubert** [comment]
This issue can cause real problems when using a module bundler such as `rollup.js`, which can cause these classes to be renamed to names that no longer correspond to the event names that should be used, thereby breaking any code that expects `ldapjs` to produce these event names as documented.

The linked pull request looks good to me, it solves the problem that I've encountered.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
