### ISSUE TITLE
Expected 0x2: got 0x63

### ISSUE THREAD

**Issue by hlatki01** [ldapjs/node-ldapjs#769]
Rocket.chat use node-ldapjs library to work with LDAP protocol, I'm getting this error and I have no clue what could be wrong:

{"level":50,"time":"2021-11-05T05:59:24.911Z","pid":1036,"hostname":"node47660-env-0554189.mg01.paas.massivegrid.net","name":"LDAP","section":"Connection","err":{"type":"VError","message":"Parser error for 3__ldap://185.85.241.129:389: Expected 0x2: got 0x63","stack":"VError: Parser error for 3__ldap://185.85.241.129:389: Expected 0x2: got 0x63<br>    at Parser.onParseError (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:890:26)<br>    at Parser.emit (events.js:314:20)<br>    at Parser.EventEmitter.emit (domain.js:483:12)<br>    at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:103:10)<br>    at Socket.onData (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:873:22)<br>    at Socket.emit (events.js:314:20)<br>    at Socket.EventEmitter.emit (domain.js:483:12)<br>    at addChunk (_stream_readable.js:297:12)<br>    at readableAddChunk (_stream_readable.js:272:9)<br>    at Socket.Readable.push (_stream_readable.js:213:10)<br>    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)<br>    at TCP.callbackTrampoline (internal/async_hooks.js:126:14)","jse_shortmsg":"Parser error for 3__ldap://185.85.241.129:389","jse_cause":{"type":"Error","message":"Expected 0x2: got 0x63","stack":"InvalidAsn1Error: Expected 0x2: got 0x63<br>    at newInvalidAsn1Error (/app/bundle/programs/server/npm/node_modules/asn1/lib/ber/errors.js:7:13)<br>    at Reader._readTag (/app/bundle/programs/server/npm/node_modules/asn1/lib/ber/reader.js:230:11)<br>    at Reader.readInt (/app/bundle/programs/server/npm/node_modules/asn1/lib/ber/reader.js:146:15)<br>    at Parser.getMessage (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:116:25)<br>    at Parser.write (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:96:20)<br>    at Socket.onData (/app/bundle/programs/server/npm/node_modules/ldapjs/lib/client/client.js:873:22)<br>    at Socket.emit (events.js:314:20)<br>    at Socket.EventEmitter.emit (domain.js:483:12)<br>    at addChunk (_stream_readable.js:297:12)<br>    at readableAddChunk (_stream_readable.js:272:9)<br>    at Socket.Readable.push (_stream_readable.js:213:10)<br>    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)<br>    at TCP.callbackTrampoline (internal/async_hooks.js:126:14)","name":"InvalidAsn1Error"},"jse_info":{},"name":"VError"},"msg":"Parser error for 3__ldap://185.85.241.129:389: Expected 0x2: got 0x63"}

**Comment by UziTech** [comment]
> InvalidAsn1Error: Expected 0x2: got 0x63

That usually means something received the wrong type. The types at https://ldap.com/ldapv3-wire-protocol-reference-asn1-ber/ seem to indicate it was looking for an `Integer` but received a `Search Request Protocol Op`

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
