### ISSUE TITLE
 create client and it  error but i got two times

### ISSUE THREAD

**Issue by JasenYang** [ldapjs/node-ldapjs#801]
![image](https://user-images.githubusercontent.com/16620382/164415478-8ef9390b-7393-4727-a8db-62a12d1cf98a.png)

` const clientOps = {
        BASE_DN: "dn=admin,dc=example,dc=com",
        bindCredentials: "123456",
        bindDN: "dc=example,dc=com",
        host: "127.0.0.1",
        port: "389",
        queryCriteria: "dn",
        url: "ldap://127.0.0.1/cn=admin,dc=example,dc=com",
    }

    const client = ldap.createClient(clientOps);
    let i = 1;
    client.on('error', (err) => {
        console.log(`ldap error time : ${i}`)
        i++;
    })`

output
`ldap error time : 1
ldap error time : 2`

**Comment by jsumners** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
