### ISSUE TITLE
Documentation shows false implementation

### ISSUE THREAD

**Issue by OrbiterToad** [ldapjs/node-ldapjs#802]
Hello There i just got started with ldapjs and there doesn't seem to be a fine example of how to use starttls
`https://github.com/ldapjs/node-ldapjs/blob/master/docs/client.md#starttls`

Doc says usage is `starttls(options, controls, callback)`

But example says 

```js
const opts = {
  ca: [fs.readFileSync('mycacert.pem')]
};

client.starttls(opts, (err, res) => {
  assert.ifError(err);

  // Client communication now TLS protected
});
```

But doesnt seem to be an optional param:

```js
Client.prototype.starttls = function starttls (options, controls, callback, _bypass) {
  //...
}
```

how do i properly create tls upgrade with the starttls method? or better how do i create/use the control?

**Comment by jsumners** [comment]
The control is added by the `starttls` method:

https://github.com/ldapjs/node-ldapjs/blob/9143456b4fa2e07127fb1fd37677fdfd4c73a6c5/lib/client/client.js#L744-L748

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
