### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by honzahajek** [ldapjs/node-ldapjs#820]
https://stackblitz.com/edit/vite-ldap?file=main.js&terminal=dev

**Comment by jsumners** [comment]
What am I supposed to understand from this issue?

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
