### ISSUE TITLE
ldapjs search not working in the production mode

### ISSUE THREAD

**Issue by perumalsamy1518** [ldapjs/node-ldapjs#822]
We are using 
`
$ node --version
v16.13.0

"ldapjs": "^2.3.3"

`

But it's working perfectly in the development mode.
How can I resolve the issue?

**Comment by jsumners** [comment]
I have no idea what you are describing. This library does not have "modes". Please provide a minimal reproduction.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
