### ISSUE TITLE
How can we create ou

### ISSUE THREAD

**Issue by imkhanzada93** [ldapjs/node-ldapjs#827]
Is it possible to create ou with sample code and explaination

**Comment by jsumners** [comment]
Did you try https://github.com/ldapjs/node-ldapjs/blob/92dfc80fd169f889cf2e0de53ff140ef2887c1c7/docs/client.md#add?

**Comment by imkhanzada93** [comment]
yes, I did try this but end up on error 

> 00000057: LdapErr: DSID-0C090CB7, comment: Error in attribute conversion operation, data 0, v1db1

**Here is my code for reference**
const sUsername = oRequest.ouName

let entry = {
    cn: sUsername,
    sn: 'bar',
    email: ['foo@bar.com', 'foo1@bar.com'],
    objectclass: 'fooPerson'
};
let DN = 'cn=' + sUsername + ',ou=' + sUsername + ',' + this.dc;
return new Promise(async (resolve, reject) => {
    this.ADConnnection.add(DN, entry, (err, res) => {
        if (err) {
            console.log(err)
            reject(err);
        } else {
            console.log(res)
            resolve(true);
        }
    });
    await this.closeConnection()
});

**Comment by jsumners** [comment]
https://duckduckgo.com/?q=%22Error+in+attribute+conversion+operation%2C+data+0%2C+v1db1%22&t=vivaldi&ia=web

**Comment by imkhanzada93** [comment]
Issue is resolve by the following code.

```
async createOU(oRequest) {
    const ouName = oRequest.ouName
    let DN = 'ou=' + ouName + ',' + this.dc;
    let entry = {
        objectclass: ADConstant.AD_PARAMS.OU_GROUP,
    };
    return new Promise(async (resolve, reject) => {
        this.ADConnnection.add(DN, entry, (err, res) => {
            if (err) {
                reject(err);
            } else {
                resolve(true);
            }
        });
        await this.closeConnection()
    });
};
```
