### ISSUE TITLE
ldapjs can't handle a well known container query

### ISSUE THREAD

**Issue by dmulder** [ldapjs/node-ldapjs#828]
To query for a well known container in Active Directory, you supply the query with a baseDN that's [formatted in an unusual way](https://learn.microsoft.com/en-us/windows/win32/ad/binding-to-well-known-objects-using-wkguid).

ldapjs fails when presented with this query:

```
node_modules/ldapjs/lib/dn.js:212
    if (beg === cur) { throw invalidDN(name) }
                       ^

Error [InvalidDistinguishedNameError]: <WKGUID=A9D1CA15768811D1ADED00C04FD8D5CD,dc=dmtest,dc=suse,dc=de>
    at invalidDN ( node_modules/ldapjs/lib/dn.js:8:13)
    at parseAttrType ( node_modules/ldapjs/lib/dn.js:212:30)
    at parseRdn ( node_modules/ldapjs/lib/dn.js:171:20)
    at Object.parse ( node_modules/ldapjs/lib/dn.js:290:13)
    at ensureDN ( node_modules/ldapjs/lib/client/client.js:85:15)
    at Client.search ( node_modules/ldapjs/lib/client/client.js:596:18)
```

**Comment by jsumners** [comment]
Can you bind using the OpenLDAP or UnboundID tools?

**Comment by dmulder** [comment]
It works with the python ldap module. Let me try with ldapsearch.

**Comment by dmulder** [comment]
It works with ldapsearch.
```sh
> ldapsearch -H ldaps://dmtest.suse.de -D "Administrator@dmtest.suse.de" -w <PASSWORD> -b "WKGUID=A9D1CA15768811D1ADED00C04FD8D5CD,dc=dmtest,dc=suse,dc=de>" -s sub "(objectClass=container)" | grep distinguishedName
distinguishedName: CN=Users,DC=dmtest,DC=suse,DC=de
```

**Comment by jsumners** [comment]
Can you try without the angle brackets (`<` and `>`)? I suspect the other tools are removing them.

**Comment by dmulder** [comment]
That fixes the 'invalidDN' error, but then the I get a 'NoSuchObjectError' error.

**Comment by dmulder** [comment]
Here's some code to reproduce:

```js
const ldap = require('ldapjs');
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

class LdapConnection {
	constructor(url, bindDN, username, password) {
		this.bindDN = bindDN;
		var opts = {
			url: url,
			bindDN: this.bindDN,
		};
		this.client = ldap.createClient(opts);
		this.bind_opts = {
			username: username,
			password: password
		};
	}

	search(opts, callback) {
		this.client.bind(this.bind_opts.username, this.bind_opts.password, err => {
			if (err) {
				console.error(err);
				return;
			}

			let response = [];
			this.client.search(opts.baseDN, opts, (err, res) => {
				if (err) {
					console.error(err);
					return;
				}

				res.on('searchEntry', (entry) => {
					response.push(entry.object)
				});

				res.on('error', (err) => {
					console.error(err);
				});

				res.on('end', (result) => {
					this.client.unbind();
					callback(err, response);
				});
			});
		});
	}

	well_known_container(container, callback) {
		var wkguiduc = null;
		if (container == 'system') {
			wkguiduc = 'AB1D30F3768811D1ADED00C04FD8D5CD';
		} else if (container == 'computers') {
			wkguiduc = 'AA312825768811D1ADED00C04FD8D5CD';
		} else if (container == 'dcs') {
			wkguiduc = 'A361B2FFFFD211D1AA4B00C04FD7D83A';
		} else if (container == 'users') {
			wkguiduc = 'A9D1CA15768811D1ADED00C04FD8D5CD';
		}
		var opts = {
			baseDN: '<WKGUID=' + wkguiduc + ',' + this.bindDN + '>',
			//baseDN: 'WKGUID=' + wkguiduc + ',' + this.bindDN,
			scope: 'sub',
			filter: '(objectClass=container)',
			attributes: ['distinguishedName']
		};
		this.search(opts, callback);
	}
}

const ldapConnection = new LdapConnection('ldaps://<SERVER>', 'dc=example,dc=com', 'Administrator@example.com', '<PASSWORD>');

ldapConnection.well_known_container('users', function(err, results) {
	console.log('Well Known Users Container:');
	if (err) {
		console.log('ERROR: ' + JSON.stringify(err));
		return;
	}
	_.each(results.other, function(other) {
		console.log(JSON.stringify(other));
	});
});
```

**Comment by dmulder** [comment]
If you need an ADDC, you can spin one up from the registry.opensuse.org/opensuse/samba-ad-dc podman/docker container.
I use this command to start one:
```sh
sudo podman run --privileged -p 53:53 -p 53:53/udp -p 88:88 -p 88:88/udp -p 123:123/udp -p 135:135 -p 137:137/udp -p 138:138/udp -p 139:139 -p 389:389 -p 389:389/udp -p 445:445 -p 464:464 -p 464:464/udp -p 636:636 -p 3268:3268 -p 3269:3269 --volume=/var/lib/samba/sysvol:/var/lib/samba/sysvol --volume=/etc/samba:/etc/samba --volume=/var/lib/samba/private:/var/lib/samba/private registry.opensuse.org/opensuse/samba-ad-dc -p example.com:<PASSWORD>
```

If it fails to bind on one of the ports, check to see if they are being used:
```sh
for port in 53 88 123 135 137 138 139 389 445 464 636 3268 3269; do
        echo "PORT ${port}"
        sudo lsof -i :${port}
done
```

**Comment by dmulder** [comment]
I just remembered there is an alternate syntax for requesting these, by just fetching the 'wellKnownObjects' attribute from the base DN. So I can work around this.

**Comment by jsumners** [comment]
Cool. I don't trust samba implementations to be 100% accurate to Active Directory. So I wouldn't consider that a completely viable reproduction. 

My current work on v3 is deep into reworking the DN parser. So this is likely to be improved in v3, but maybe not. I have not seen anything in the RDN spec that indicates that syntax is valid.

**Comment by dmulder** [comment]
> @dmulder I didn't realize you are a member of the Samba team. I meant no offense by the compatibility statement. It's really about ActiveDirectory being a closed product.

Lol, no offense taken.

> Anyway, I'm looking at your suggestion as a way to support the `activedirectory2` module. It looks like that container is managed out of https://github.com/dmulder/container-images/, but that repo does not allow issues to be opened. So I hope you are willing to answer some basic questions here.

That container is actually managed here: https://github.com/openSUSE/container-images

> ❯ docker run --rm -it --name samba-ad-dc -p 1389:389 -e 'DEBUG=1' registry.opensuse.org/opensuse/samba-ad-dc -p example.com:1234567

...

> + samba-tool domain provision --domain=example --realm=example.com --adminpass=1234567 --host-name=4aaa63d53fa1 --function-level=2008_R2
> ERROR: Administrator password does not meet the default quality standards

...

> Does this look correct to you?

No, it does not ;-)
The password you chose is bad. Samba will fail to provision a domain if the password doesn't meet specific complexity requirements.

**Comment by dmulder** [comment]
Maybe I should add a check to make sure the provision succeeded before attempting to start the daemon. Otherwise we end up with ugly errors like this.

**Comment by dmulder** [comment]
I went ahead and ran your that command with a better password, and there are still errors. You're missing some critical components in your command.

The ADDC cannot start in usermode, and it cannot start without privileges. So you MUST run it as root, and with `--privileged`.

**Comment by dmulder** [comment]
One more thing, you will need to fix the dns records inside the host after it starts.
Point your resolv.conf to localhost (this will require opening dns ports on the container), then run:

`samba-tool dns update example.com example.com example.com A 172.17.0.2 192.168.1.88 -UAdministrator`

Where 172.17.0.2 is the invalid address added via podman, and 192.168.1.88 is the real host address.

I'm not sure if this is necessary with what you're working on, but it certainly caused me some trouble to have the dns record pointing at the internal container ip.

**Comment by jsumners** [comment]
> The password you chose is bad. Samba will fail to provision a domain if the password doesn't meet specific complexity requirements.

Clearly it isn't a "production" use password.

> The ADDC cannot start in usermode, and it cannot start without privileges. So you MUST run it as root, and with `--privileged`.

😕

-----

Thank you for taking the time to respond. I think I'm going to say that it is not worth the trouble. All of what you wrote is _just_ to get the thing started. I'm sure it would be even more of a challenge to bootstrap it with test data.

**Comment by dmulder** [comment]
¯\_(ツ)_/¯ up to you. If you're more familiar with Windows, then a Windows ADDC may be easier for you.

**Comment by jsumners** [comment]
I have never administered an ADDC. I have had to use them in the past, but primarily through LDAP.

**Comment by dmulder** [comment]
Well, you should be able to get up and running with this command:

```
sudo docker run --privileged -p 53:53 -p 53:53/udp -p 88:88 -p 88:88/udp -p 123:123/udp -p 135:135 -p 137:137/udp -p 138:138/udp -p 139:139 -p 389:389 -p 389:389/udp -p 445:445 -p 464:464 -p 464:464/udp -p 636:636 -p 3268:3268 -p 3269:3269 registry.opensuse.org/opensuse/samba-ad-dc -p example.com:Test1234
```
You could probably just communicate with ldap via the container IP, and not mess with fixing dns.
