### ISSUE TITLE
SyntaxError: Unexpected token = at node_modules\ldapjs\lib\client\client.js:1122 messageID = msgid

### ISSUE THREAD

**Issue by prithvikreddy** [ldapjs/node-ldapjs#840]
All of a sudden, project fails to start with below error in **production today**( Deployed to prod, where npm install step was successful but app couldn't start because of this error). We are using "activedirectory": "^0.7.2" package which is dependent on ldapjs. 

**Observation:**: Looks like  jsumners made on update on 2023-02-16 at node_modules\ldapjs\lib\client\client.js:1122 might be the cause for the issue, not sure. Its attached in the screenshot. Below is the code and screenshot from  node_modules\ldapjs\lib\client\client.js:

![image](https://user-images.githubusercontent.com/25291777/220946440-def323fc-609a-4779-b331-4e0393cd4747.png)

```

tracker.purge(function (msgid, cb) {
    if (socket.unbindMessageID !== msgid) {
      return cb(new ConnectionError(tracker.id + ' closed'))
    } else {
      **// Unbinds will be communicated as a success since we're closed
      // TODO: we are faking this "UnbindResponse" object in order to make
      // tests pass. There is no such thing as an "unbind response" in the LDAP
      // protocol. When the client is revamped, this logic should be removed.
      // ~ jsumners 2023-02-16**
      const Unbind = class extends LDAPResult {
        **messageID = msgid** // This is ldapjs\lib\client\client.js:1122  messageId = msgid
        status = 'unbind'
      }
      const unbind = new Unbind()
      return cb(unbind)
    }
  })

```

Nodejs version: v613.1
npm version: 3.10.10

```
**Error:** C:\cws\Projects\OPA-OWA\OPA-Document\node_modules\ldapjs\lib\client\client.js:1122
        messageID = msgid
                  ^
SyntaxError: Unexpected token =
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\cws\Projects\OPA-OWA\OPA-Document\node_modules\ldapjs\lib\client\index.js:4:16)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\cws\Projects\OPA-OWA\OPA-Document\node_modules\ldapjs\lib\index.js:5:16)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
```

![image](https://user-images.githubusercontent.com/25291777/220939748-4fbff7df-09f7-4ba8-897a-c64a2c374bb5.png)

**Comment by jsumners** [comment]
You seem to be using `ldapjs@3` ([released yesterday](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0)). It is a major change version and as such you should do testing in your environment before you blindly install it in production.

You state that you are using `activedirectory@0.7.2`. That package has not been maintained in over 7 years. The `activedirectory2` package is _more recently_ maintained, but is also unlikely to work without changes.

You state that your Node.js version is "613.1". I do not recognize this version number. What I can say is that `ldapjs@3` has been tested on the current versions of Node.js: version 16, 18, and 19.

Given the above, I am closing this issue as unsupported. If you can provide a reproduction with a modern environment, feel free to re-open.

**Comment by prithvikreddy** [comment]
Hello Jsumners, 

Thanks for the response.  Node version is v6.13.1.

ldapjs is not direct dependency in our package.json. Looks like activedirectory@0.7.2 uses ldapjs. So, is it fair to say that activedirectory@0.7.2 is installing latest ldapjs@3? 

Can we use activedirectory2 on nodev6? 
This is very old project if I update to node 16 or up it will have breaking changes! What options do I have now?

I appreciate your response. Thank you.

**Comment by jsumners** [comment]
1. Node v6.13.1 has not been supported in years. See https://github.com/nodejs/release#release-schedule
2. Yes, the `activedirectory` package relies upon the `ldapjs` package. It is doing so with a `>=` qualifier, so it is installing whatever version of `ldapjs` is the latest (https://github.com/gheeres/node-activedirectory/blob/416b201e188d7748bbaaaf888eba131c4bf6ebd4/package.json#L23). This is an incorrect way to manage dependencies
3. The minimum supported version of Node for `activedirectory2` is Node.js 10 -- https://github.com/jsumners/node-activedirectory/blob/8ff17bdf366a2d6926879ba06fbe84ba0171c01f/.github/workflows/ci.yml#L10. But again, that package will surely need updates to work with `ldapjs@3`.

> This is very old project if I update to node 16 or up it will have breaking changes!

You already have breaking changes by virtue of the way you are managing your dependencies.

> What options do I have now?

At a minimum, you should pin your dependencies to known working versions. But you really should be putting in the effort to modernize your dependencies. None of them that you have listed are supported, and there are known security vulnerabilities throughout that stack.

**Comment by brvendrametto** [comment]
I had a similar error, for the same dependency reason.
Changing Node version was unfeasible for me. I solved it by installing ldapjs in my package.
npm i ldapjs@2.3.3
