### ISSUE TITLE
Apache Directory Studio don't find schema to new entries

### ISSUE THREAD

**Issue by calebeaires** [ldapjs/node-ldapjs#842]
While creating a server with ldapjs, 

To add new entries, Apache Directory Studio ask for a schema to preset the new entry. Doing so, I have prepared this configuration:

```ts
            this.server.search('', function (req, res, next) {
                console.log('clearn search');

                res.send({
                    attributes: {
                        objectclass: ['top', 'person', 'OpenLDAProotDSE'],
                        dc: 'test',
                        o: 'test',
                        subschemaSubentry: ['cn=subschema']
                    },
                    dn: 'ou=users'
                });

                res.end();
                next();
            });

            this.server.search('cn=subschema', function (req, res, next) {
                console.log('subschema');
                res.send({
                    attributes: { objectclass: ['*'] },
                    dn: 'cn=example@gmail.com,ou=user,ou=users'
                });
                res.end();
                next();
            });

```

Here is how I tried to create a new entry:

![CleanShot 2023-03-02 at 19 18 49@2x](https://user-images.githubusercontent.com/794195/222572211-a6deb847-5386-4aad-93dd-05b1c97917ab.png)

As you see, the attribute object class is empty. There is no schema even if the schema set in the server is loaded.

![CleanShot 2023-03-02 at 19 18 15@2x](https://user-images.githubusercontent.com/794195/222571921-7dc9e1de-013a-49c7-a0f9-f80b1e766037.png)

How to make it happen? How to use subschemaSubentry to pre-define a schema so the Apache Directory User cant add new entries based on some schema?

**Comment by jsumners** [comment]
Sorry, but this does not seem to be an issue with the `ldapjs` module. The module provides you with a framework with which you can build a server that "speaks LDAP". It's up to you to implement the bits necessary for the LDAP conversations you expect.

I suggest reading https://ldap.com/understanding-ldap-schema/. In particular, read https://ldap.com/retrieving-schema-over-ldap/.
