### ISSUE TITLE
v3 server.search change scope names

### ISSUE THREAD

**Issue by ahaenggli** [ldapjs/node-ldapjs#845]
Following the example of an [in memory server](http://ldapjs.org/examples.html#in-memory-server) server.search uses 3 scopes: base, one, sub
With v3 it looks like [*one*](https://github.com/ldapjs/node-ldapjs/blob/v2.3.3/lib/messages/search_request.js#L54) is now [*single*](https://github.com/ldapjs/messages/blob/4c82e476d1749cd1b699c49f070dd95b8c0fa3cf/lib/messages/search-request.js#L11) and *sub* is now called *subtree*. This looks like a breaking change for server implementations to me. The adjustment is of course made very quickly on server side code.

**Comment by jsumners** [comment]
Are you suggesting that the v2 values are not working? They should be according to the tests -- https://github.com/ldapjs/messages/blob/4c82e476d1749cd1b699c49f070dd95b8c0fa3cf/lib/messages/search-request.test.js#L187-L202

**Comment by ahaenggli** [comment]
The v2 values would work. But with v3, server.search receives the v3 values as req.scope.
So the v3 values must be added in each server.search implementation, otherwise they will not be processed:

```javascript

server.search(SUFFIX, authorize, (req, res, next) => {
  const dn = req.dn.toString();
...
...
  switch (req.scope) {
  case 'base':
...
  case 'one':
  case 'single:
...
  case 'sub':
  case 'subtree':
...
}
...
...
```
