### ISSUE TITLE
SASL bind support

### ISSUE THREAD

**Issue by esamattis** [ldapjs/node-ldapjs#85]
There seem to be some TODOs in the code about this. Just creating a ticket to track its progress if you don't mind.

**Comment by FROGGS** [comment]
Isnt this issue a duplicate of #29 ?

**Comment by jsumners** [comment]
> Isnt this issue a duplicate of #29 ?

I don't know. I have not investigated the two terms enough to say that they are the same.

**Comment by jsumners** [comment]
👋

On February 22, 2023, we released [version 3](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) of this library. As a result, we are closing this issue/pull request.

Please see [issue #839](https://github.com/ldapjs/node-ldapjs/issues/839) for more information, including how to proceed if you feel this closure is in error.
