### ISSUE TITLE
Why is ldap not more popular? Advantages of node-ldapjs over auth0? auth.js and ldapjs? passport-ldpauth?

### ISSUE THREAD

**Issue by SylvianHemus** [ldapjs/node-ldapjs#855]
Hello fellow travelers on the wayside
I am curious as to why ldap as a standard is not more commonly used for authentication for webapps. People typically roll their authentication using a database like sql or mongo and hashing using something like passport or auth.js. From my perspective, it's a good idea to stick with the standards and the basics, especially one as old as ldap.

I recently learned about ldap as an authentication method because I need a way to maintain user namespaces (for email) in a way agnostic from the containers that refer to them.  

What is the advantage of using node-ldapjs over say auth0? https://auth0.com/docs/authenticate/identity-providers/enterprise-identity-providers/active-directory-ldap

Also I'm slightly confused, there's ldapjs referenced by auth.js https://authjs.dev/guides/other/ldap-auth - this is the same project, right? 

There's also passport-lpdauth https://www.passportjs.org/packages/passport-ldapauth/

**Comment by jsumners** [comment]
> What is the advantage of using node-ldapjs over say auth0?

They are not mutually exclusive.

> Also I'm slightly confused, there's ldapjs referenced by auth.js https://authjs.dev/guides/other/ldap-auth - this is the same project, right?

We are not affiliated with "auth.js". Yes, the `ldapjs` they suggest using is this module.

-----

To address the overall question: people make their own determinations as to how they will manage their account databases. Some will use an LDAP server, others a RDBMS. We have no opinion on what someone should use. We are not designing their systems and don't know their requirements.
