### ISSUE TITLE
corresponding field in v3 of the `raw` field in v2

### ISSUE THREAD

**Issue by shaozi** [ldapjs/node-ldapjs#858]
In v2, in ldap client `search` function, on `searchEntry` event callback, the `entry` parameter has a `raw` field:

```javascript
ldapClient.search(searchBase, searchOptions, function (err, res) {
//...
  res.on('searchEntry', function (entry) {
        user = entry.object
        user.raw = object.raw
      })
```
What is the corresponding `raw` field in the new `entry` or `entry.pojo` in v3?

**Comment by jsumners** [comment]
It's not clear what the purpose of `.raw` is:

https://github.com/ldapjs/node-ldapjs/blob/92dfc80fd169f889cf2e0de53ff140ef2887c1c7/lib/messages/search_entry.js#L64-L88

You should use the methods native to the `SearchResultEntry` object. See https://github.com/ldapjs/messages/blob/b37b2f5fe400d09deea47103f609a8c29a86452d/lib/messages/search-result-entry.js

**Comment by christopherpickering** [comment]
@jsumners raw was added to be able to get images through a buffer. See this issue https://github.com/ldapjs/node-ldapjs/issues/290

Is there a better way to get the image buffers?

**Comment by christopherpickering** [comment]
I went on a treasure hunt and found the answer :)
Adding a `;binary` at the end of the attributes requested will give the correct base64 back and it doesn't need to be converted as we did w/ the `.raw` stuff.

https://github.com/ldapjs/attribute/blob/d1cba4723fb6953a932a71b53a8d842eeab564c7/index.js#L23

This seems to be a new features (at least I couldn't find it in v2) Thanks @jsumners :)

**Comment by jsumners** [comment]
How would you notate this change in the v3 release notes, @christopherpickering?

**Comment by christopherpickering** [comment]
`.raw` search entry property has been removed. It was used to access binary attribute. Binary attributes can now be accessed by appending `;binary` to the attribute name.

Hows that sound?

**Comment by jsumners** [comment]
I have updated the [v3 release notes](https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0) with this information.

**Comment by GisCat** [comment]
While using searchEntry in v2 I was able to acces to the entry result like this:
```
res.on('searchEntry', async (entry: any) => {
             console.log("entry.dn ",entry.dn);
             console.log("entry.attributes ",entry.attributes);
}
```
But in v3 I got an empty objcts instead of my fields, what do I need to change ?

**Comment by shaozi** [comment]
> While using searchEntry in v2 I was able to acces to the entry result like this:
> 
> ```
> res.on('searchEntry', async (entry: any) => {
>              console.log("entry.dn ",entry.dn);
> }
> ```
> 
> But in v3 I got an empty objcts instead of my fields, what do I need to change ?

I believe in v3 the dn is `entry.objectName`
