### ISSUE TITLE
The unknown protocol caused the service to crash

### ISSUE THREAD

**Issue by 77321660** [ldapjs/node-ldapjs#862]
message: 'Parser error for 172.20.1.174:58860: Parser error for 172.20.1.174:58860: Op 0x?? not supported'
![image](https://user-images.githubusercontent.com/3907055/227866832-ff0cd5ad-3111-44a9-9f25-4058ae247623.png)

How to handle exceptions gracefully so that the service does not crash？

**Comment by jsumners** [comment]
Thank you for reporting, but there is not nearly enough information to provide any assistance. Please provide a [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_reproducible_example).
