### ISSUE TITLE
replace documentation doesnt match with actual behaviour in 3.0.2

### ISSUE THREAD

**Issue by tomnil** [ldapjs/node-ldapjs#865]
Reading the documentation, I would assume this works (it works fine for version 2).

```javascript
const change = new ldap.Change({
  operation: 'replace',
  modification: {
    pets: ['cat', 'dog']
  }
});
```

The defined interface `Change` also suggest that this should work.

```javascript
export interface Change {
    operation: string;
    modification: {
        [key: string]: any;
    };
}
```

What's acutally needed in order to pass the `Attribute.isAttribute` check (if not done like this, an error of `modification must be an Attribute` will be thrown).

```javascript
const input: ldapjs.Change = {
	operation: 'replace',
	modification: {
		type: "pets",
		values: ['cat', 'dog']
	}
};
```

Ps. As a bonus, change the interface to:

```typescript
export interface Change {
    operation: "add" | "delete" | "replace";
    modification: {
        [key: string]: string | number | whatever-is-allowed-here;
    };
}
```

**Comment by jsumners** [comment]
Can you provide a link to the documentation you are referring to?

**Comment by ewalti** [comment]
just bumped into this myself: http://ldapjs.org/client.html#modify

> Example:

```
const change = new ldap.Change({
  operation: 'add',
  modification: {
    pets: ['cat', 'dog']
  }
});

client.modify('cn=foo, o=example', change, (err) => {
  assert.ifError(err);
});
```

**Comment by jsumners** [comment]
Thanks. Would you care to submit a PR that follows the recommendation in the v3 release notes?

**Comment by tomnil** [comment]
Will not fix.

**Comment by jsumners** [comment]
The documentation should be updated.

**Comment by mihir254** [comment]
> The documentation should be updated.

I'd like to help with that
