### ISSUE TITLE
Cannot retrive objectName from searchEntry when I update ldapjs to v3

### ISSUE THREAD

**Issue by GisCat** [ldapjs/node-ldapjs#870]
While parsing searchEntry callback in v2 I was able to acces to the entry result:
```
res.on('searchEntry', async (entry: any) => {
             console.log("entry.dn ",entry.objectName);
}
```
But in v3 I got an empty objcts instead of my fields, what do I need to change ? 
I used this code to get closer but without success:
```
res.on('searchEntry', async (entry: any) => {
             console.log('entry: ' + JSON.stringify(entry.pojo));
}
```

**Comment by GisCat** [comment]
I found the solution, I added .pojo to access to the object:
```
res.on('searchEntry', async (entry: any) => {
             console.log('entry: ' + JSON.stringify(entry.pojo.objectName));
}
```

**Comment by jsumners** [comment]
Please ready the v3 release notes https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0
