### ISSUE TITLE
[LDAP_ATTRIBUTE_DEP_003] LdapjsAttributeWarning: Instance property .vals is deprecated. Use property .values instead.

### ISSUE THREAD

**Issue by tomnil** [ldapjs/node-ldapjs#871]
When running, I get this in the output:

```
[LDAP_ATTRIBUTE_DEP_003] LdapjsAttributeWarning: Instance property .vals is deprecated. Use property .values instead.
```

Unfortunalety doesn't class Attribute expose .values (which is used by, for example, ```ldapjs.SearchEntry```):

```typescript
export class Attribute {
    constructor(options?: { type?: string; vals?: any });
    readonly type: string;
    readonly buffers: Buffer[];

    /**
     *  Array of string values, binaries are represented in base64.
     *  get: When reading it always returns an array of strings.
     *  set: When assigning it accepts either an array or a single value.
     *       `Buffer`s are assigned directly, any other value is converted to string and loaded into a `Buffer`.
     */
    vals: string | string[];

    readonly json: AttributeJson;

    /** Stringified json property */
    toString(): string;

    static isAttribute(object: any): object is Attribute;
    static compare(a: Attribute, b: Attribute): number;
}
```

**Comment by jsumners** [comment]
I don't know what code you are quoting. It is clearly defined at https://github.com/ldapjs/attribute/blob/d1cba4723fb6953a932a71b53a8d842eeab564c7/index.js#L88-L93

**Comment by BrunoMonteiro92** [comment]
Same issue here
![image](https://github.com/ldapjs/node-ldapjs/assets/2872959/e78f193a-de80-4d4b-a807-fa29cea586dc)

**Comment by jsumners** [comment]
> I don't know what code you are quoting. It is clearly defined at https://github.com/ldapjs/attribute/blob/d1cba4723fb6953a932a71b53a8d842eeab564c7/index.js#L88-L93

**Comment by tomnil** [comment]
I guess it's beacuse the types for v2 and v3 mismatches. Unfortunalety it wont be fixed: https://github.com/ldapjs/node-ldapjs/issues/893

**Comment by jsumners** [comment]
In order for something to be "fixed" it must first be broken. `ldapjs` is a JavaScript module for JavaScript applications. No one who has ever administered this project has provided any TypeScript, or other language, types. If some third party is doing so, and you rely upon their work, you must take it up with them. Anyone is welcome to use `ldapjs` in whatever language they wish, but we only provide support for JavaScript.
