### ISSUE TITLE
Bad Method Definition

### ISSUE THREAD

**Issue by ryanbsaic** [ldapjs/node-ldapjs#877]
node-ldapjs version 3.0.2
Webpack 5.76.3
ReactJS

Getting "bad method defintion" error pointing to ldapjs/lib/client/index.js: const Client = require('./client')

Any ideas?

**Comment by jsumners** [comment]
I don't know what you're asking.

**Comment by ryanbsaic** [comment]
Really? Thought you could infer from my comment that I'm wondering why I'm getting that error. Why is "bad method definition" being thrown from that line in that file using the above versions?

**Comment by jsumners** [comment]
Our test suite evaluates the line presented as a problem via:

1. https://github.com/ldapjs/node-ldapjs/blob/7fc99fd721cadf148a259cdbe35b22580a4dfeef/test/client.test.js#L13

2. https://github.com/ldapjs/node-ldapjs/blob/7fc99fd721cadf148a259cdbe35b22580a4dfeef/lib/index.js#L5

If you are able to provide a minimal reproduction, we will attempt to help you. As it is, we cannot reproduce the issue.

**Comment by ryanbsaic** [comment]
Thanks! Quick quesiton...are you including ldapjs in a React/webpack app? In other words, are you running "npm start"? Or are you running node <filename>. I'm a python/Java developer and brand new to JS. Thank you for your patience.

**Comment by ryanbsaic** [comment]
I'm Melllltinnnngggg (Wicked Witch voice)
