### ISSUE TITLE
When I was modifying the entry attribute, I found that the attribute case was converted to lowercase

### ISSUE THREAD

**Issue by WilliamGrant** [ldapjs/node-ldapjs#882]
Hi bro! when I used the client to send a entry for the server, I found that the defined attributes were converted to lowercase attribute names before being transmitted to the server. I mean used the add action.I found in @ldap/message lib -> add-request.js
This problem may come from the parseToPojo method (262 lines of code). Is it deliberately written like this? I want to know if it is a bug or it is designed like this.

```
while (ber.offset < endOfAttributesPos) {
      const attribute = Attribute.fromBer(ber)
      attribute.type = attribute.type.toLowerCase()

      if (attribute.type === 'objectclass') {
        for (let i = 0; i < attribute.values.length; i++) {
          attribute.values[i] = attribute.values[i].toLowerCase()
        }
      }

      attributes.push(attribute)
    }
```

**Comment by jsumners** [comment]
Yes, that is correct. The spec mandates that attribute types are case insensitive.

**Comment by WilliamGrant** [comment]
> Yes, that is correct. The spec mandates that attribute types are case insensitive.

ok~  i see
 thanks!
