### ISSUE TITLE
Encoding error in AD server when sending non-English values as CN attribute

### ISSUE THREAD

**Issue by glozeus** [ldapjs/node-ldapjs#883]
When sending Korean values in the format of CN=홍길동 to the AD server, it appears as íê¸¸ë with garbled characters. Is there any way to resolve this issue?

![image](https://github.com/ldapjs/node-ldapjs/assets/130005494/063d3947-0e58-480f-ad13-3b10621d8332)

**Comment by glozeus** [comment]
-- code

	client.bind(connection.username, connection.password, function (err) {
        if (err) {
            console.log("Error in new connetion " + err)
        } else {

          var entry = {
            objectclass: 'user',
            };

           // const nm = 'HGD' //English ADD Succcess.
           const nm = '홍길동' //Korean ADD Succcess. but the characters are corrupted and saved

            const dn = 'CN=' + nm + ',OU=a,DC=zeus,DC=com';

            client.add(dn, entry, function (err) {
                if (err) {
                    console.log("err in new user " + err);
                } else {
                    console.log("added user")
                }
            });
        }

![image](https://github.com/ldapjs/node-ldapjs/assets/130005494/10f10d5d-f556-4b1d-8839-c80785a926ed)


When Korean characters are included in CN, they get corrupted and additional characters are added.

**Comment by jsumners** [comment]
See the test added in https://github.com/ldapjs/node-ldapjs/pull/884. The entry gets added, retrieved, and shows the same characters as was input.

**Comment by jsumners** [comment]
I am closing this due to lack of response and not being able to replicate the issue.
