### ISSUE TITLE
Question about some error?

### ISSUE THREAD

**Issue by classmatewu** [ldapjs/node-ldapjs#892]
https://github.com/ldapjs/node-ldapjs/issues/685#issuecomment-739904081

Hi, @jsumners , why do you say "If you do this, you are likely to encounter memory leaks and other errors", is it possible that the tcp connection has always existed, but does not tcp close the current socket when receiving ECONNRESET?

I am very sorry to bother you with this question. Thanks a lot.

**Comment by jsumners** [comment]
Please see the docs https://nodejs.org/api/process.html#warning-using-uncaughtexception-correctly

> Unhandled exceptions inherently mean that an application is in an undefined state. Attempting to resume application code without properly recovering from the exception can cause additional unforeseen and unpredictable issues.
