### ISSUE TITLE
International characters fail when renaming an object

### ISSUE THREAD

**Issue by tomnil** [ldapjs/node-ldapjs#894]
Passing a dn with international characters will successfylly rename the user, but the resulting dn will include encoded characters. As a result the user seems to be unaccessable from the "Active Directory Users and Computers".

## v2 behaviour:

Version 2.3.3 correctly renamed the object to `CN=Åke,DC=a,DC=b,DC=se`.

## Code

```
let client = ldapjs.createClient({ url: URL });
let oldDn = "CN=Test,DC=a,DC=b,DC=se"
let newDn = "CN=Åke,DC=a,DC=b,DC=se"
client.modifyDN(oldDn, newDn, (error: Error | null) => { ... }
```

**Comment by jsumners** [comment]
Is this a duplicate of https://github.com/ldapjs/node-ldapjs/issues/883?

**Comment by jsumners** [comment]
Please research why your LDAP server is not adhering to the spec and processing encoded DN strings correctly.
