### ISSUE TITLE
Can paging set the pageNumber?

### ISSUE THREAD

**Issue by classmatewu** [ldapjs/node-ldapjs#906]
I saw in the documentation that ldapjs provides paged capabilities, but I didn’t see the parameter that can set pageNumber. How can I set pageNumber to achieve the effect of getting a certain page of data?
> http://ldapjs.org/client.html#paging
```js
const queue = new MyWorkQueue(someSlowWorkFunction);
const opts = {
  filter: '(objectclass=commonobject)',
  scope: 'sub',
  paged: {
    pageSize: 250,
    // pageNumber: 20,
    pagePause: true
  },
};
client.search('o=largerdir', opts, (err, res) => {
  assert.ifError(err);
  res.on('searchEntry', (entry) => {
    // Submit incoming objects to queue
    queue.push(entry);
  });
  res.on('page', (result, cb) => {
    // Allow the queue to flush before fetching next page
    queue.cbWhenFlushed(cb);
  });
  res.on('error', (resErr) => {
    assert.ifError(resErr);
  });
  res.on('end', (result) => {
    console.log('done');
  });
});
```

**Comment by jsumners** [comment]
> How can I set pageNumber to achieve the effect of getting a certain page of data?

You can't. An LDAP query results in a stream of entries. "Pages" are a temporary construct that exist only for the duration of the search request:

https://datatracker.ietf.org/doc/html/rfc2696#section-3
> The server will then return the next set of results from the whole
   result set. This interaction will continue until the client has
   retrieved all the results, in which case the cookie in the
   searchResultDone field will be empty, or until the client abandons
   the search sequence as described below. Once the paged search
   sequence has been completed, the cookie is no longer valid and MUST
   NOT be used.

LDAPjs provides paged results as events in the result set stream as shown in the example quoted.
