### ISSUE TITLE
Update filter documentation

### ISSUE THREAD

**Issue by jsumners** [ldapjs/node-ldapjs#909]
The substring filter documentation is inconsistent with the current implentation. It should be updated.

> The latter are also not mentioned in the [example](http://ldapjs.org/filters.html#substringfilter).

The documentation should be updated.

Source: https://github.com/ldapjs/node-ldapjs/issues/907

**Comment by devbysn** [comment]
Hello @jsumners 
I've updated the parameters and created a pull request.
Can you verify?

**Comment by devbysn** [comment]
I am still very beginner,
i hope i didn't mess anything :)

**Comment by jsumners** [comment]
This is being resolved by https://github.com/ldapjs/filter/pull/5.
