### ISSUE TITLE
Not able to get entries with JXplorer

### ISSUE THREAD

**Issue by hotfusion** [ldapjs/node-ldapjs#917]
Hey, i hope you doing well. I am trying to manage a connection with JXplorer but have no success. Here is a  primitive example that i am trying to implement:

```
const basedn = "dc=example, dc=com";
server.bind(basedn, (req, res, next) => {
                console.log('auth')
                res.end();
                next();
});

server.search(basedn, (req, res, next) => {
                res.send({
                    dn         : "cn=whatever",
                    attributes : {
                        objectclass : ['top','organization'],
                        o           : 'site',
                        description : 'des',
                        cn          : 'contact.name',
                        mail        : 'contact.email',
                        givenname   : 'contact.firstname',
                        sn          : 'contact.surname',
                        ou          : 'company'
                    }
                });
                res.end();
                next();
});
server.listen(389);
```
Here i am trying to connect to LDAP server and it works:
![image](https://github.com/ldapjs/node-ldapjs/assets/116390360/afa0d571-70d6-44df-9cbb-3586ab02ec44)

 After i connected, i am not getting the entry "cn=whatever":
![image](https://github.com/ldapjs/node-ldapjs/assets/116390360/0c4a0a89-8ec4-4ff4-8ffe-66f50b9c4f66)

also the schema section is stuck in reading mode:
![image](https://github.com/ldapjs/node-ldapjs/assets/116390360/5bdf8d9c-f147-4788-87a7-b82f68fd1385)

I am not sure what i am doing wrong here, i suspect that ldapjs do not support other ldap clients rather only ldapjs client. I also tried to connect with apache studio directory and had no success either.  If u have a moment to give me directions on this one. Thank you!

**Comment by jsumners** [comment]
I suggest reviewing the examples https://github.com/ldapjs/node-ldapjs/blob/3c7b7cbedf1591209912964b42e168e51b68581c/docs/examples.md

What I can say for certain is that the server library is not written to only accommodate the client library. They server to distinct, independent, purposes.
