### ISSUE TITLE
Question about accessing search result attributes in v3

### ISSUE THREAD

**Issue by ecs-hk** [ldapjs/node-ldapjs#919]
I'm making the move from ldapjsv2 to v3, and I have read the release notes documentation:
* https://github.com/ldapjs/node-ldapjs/releases/tag/v3.0.0

**My question**: under v3, is there any way to access a search result attribute *directly* (like under v2) so that I don't have to iterate through an array of attributes every time?

Abbreviated example of a search result, `entry.object`, from v2:
```javascript
{
    "dn": "cn=foo,dc=org",
    "member": [
      "uid=baz",
      "uid=fuz"
    ],
    "email": "foo@org",
    "private": "FALSE"
}
```

By contrast, abbreviated example of a search result, `entry.pojo`, from v3:
```javascript
{
  "type": "SearchResultEntry",
  "objectName": "cn=foo,dc=org",
  "attributes": [
    {
      "type": "member",
      "values": [
        "uid=baz",
        "uid=fuz"
      ]
    },
    {
      "type": "email",
      "values": [
        "foo@org"
      ]
    },
    {
      "type": "private",
      "values": [
        "FALSE"
      ]
    }
}
```

Thanks for any help.

**Comment by jsumners** [comment]
I think the comments in issue #841, which is linked from the v3 release notes, are pretty clear. But, to reiterate, the v2 `.object` property was _not_ a direct access. It converted object to an object literal, i.e. serialized it to "JSON", and returned that object. So it was an expensive operation. This is exactly the way the `.pojo` accessor works.

We would definitely welcome a PR to `@ldapjs/messages` to provide utility accessors for the `SearchEntry` object. But as it stands, the best, most efficient, way to access the properties on this object are through the functional methods described in the above referenced issue.
