### ISSUE TITLE
Adding user with password attribute throws error

### ISSUE THREAD

**Issue by mihir254** [ldapjs/node-ldapjs#922]
I am using the `ldapjs` library to connect to an active directory from a `Nextjs-Nodejs` application. After creating and binding the client, I am trying to add a new user to the active directory. This is what my user object looks like:
```
const userEntry = {
    cn: accountID,
    sAMAccountName: accountID,
    userPrincipalName: `${accountID}@xyz.abc`,
    description: description,
    objectClass: ['top', 'person', 'organizationalPerson', 'user'],
};
```
With this, I was successfully able to create a new active directory user. But, since I had not included password in the user object, the new user was disabled and a flag `User must change password at next logon` was set. I want to make sure that the created user is enabled, and the `Password never expires` flag is set. Upon reading further, I realized that I need to also include the `password` and `userAccountControl` attribute to achieve this.
This is how the new user object looks like now:
```
const passwordBuffer = Buffer.from(`"${password}"`, 'utf16le');
const encodedPassword = passwordBuffer.toString('base64');
const entry = {
    cn: accountID,
    sAMAccountName: accountID,
    userPrincipalName: `${accountID}@xyz.abc`,
    unicodePwd: encodedPassword,
    description: description,
    objectClass: ['top', 'person', 'organizationalPerson', 'user'],
    userAccountControl: 512, // Normal user
};
```
Using this, `ldapjs `throws an error: `Unwilling to perform.`

There are no details of the error. I want to understand how I can set the user password for a new user created using `ldapjs`. I couldn't find resources to help me understand the password setting step. There are no such examples in the documentation either.

Please let me know where I am going wrong, or if there's a correct way of doing this. Also, how can I explore the "`Unwilling to perform` error" in depth? It displays no details regarding what must have gone wrong.

Thank you

**Comment by jsumners** [comment]
Please use formatting to make your question legible -- https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

Also, please explain how this question related to the `ldapjs` library.

**Comment by mihir254** [comment]
> Please use formatting to make your question legible -- https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
> 
> Also, please explain how this question related to the `ldapjs` library.

Updated the issue description

**Comment by jsumners** [comment]
That error maps to the standard LDAP error code `53`. See https://github.com/ldapjs/protocol/blob/58ae926cbe694c83b3d000674245b3c0115cfc77/index.js#L75

It is the server that is returning the error code. The library is translating it to a human readable representation. I imagine that if you posted the full stack trace of the error, we would see that being shown.

**Comment by mihir254** [comment]
> That error maps to the standard LDAP error code `53`. See https://github.com/ldapjs/protocol/blob/58ae926cbe694c83b3d000674245b3c0115cfc77/index.js#L75
> 
> It is the server that is returning the error code. The library is translating it to a human readable representation. I imagine that if you posted the full stack trace of the error, we would see that being shown.

Failed to add user:  LDAPError [UnwillingToPerformError]: Unwilling To Perform
    at messageCallback (C:\Users\M_Bhansali\Desktop\prep\node_modules\ldapjs\lib\client\client.js:1261:45)
    at Parser.onMessage (C:\Users\M_Bhansali\Desktop\prep\node_modules\ldapjs\lib\client\client.js:919:14)
    at Parser.emit (node:events:512:28)
    at Parser.write (C:\Users\M_Bhansali\Desktop\prep\node_modules\ldapjs\lib\messages\parser.js:135:8)
    at Socket.onData (C:\Users\M_Bhansali\Desktop\prep\node_modules\ldapjs\lib\client\client.js:875:22)
    at Socket.emit (node:events:512:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  lde_message: 'Unwilling To Perform',
  lde_dn: null
}

**Comment by mihir254** [comment]
```
{"name":"ldap","component":"client","hostname":"Z2-IZZI","pid":14744,"clazz":"Client","ldap_id":"3__ldap://patton:389","level":10,"msg":"sending request {\"messageId\":3,\"protocprotocolOp\":104,\"type\":\"AddRequest\",\"entry\":\"CN=9999-awsd,OU=XYZ,DC=Xyz,DC=abc\",\"attributes\":[{\"type\":\"cn\",\"values\":[\"9999-awsd\"]},{\"type\\"ccou":\"sAMAccountName\",\"values\":[\"9999-awsd\"]},{\"type\":\"userPrincipalName\",\"values\":[\"9999-awsd@xyz.abc\"]},{\"type\":\"unicodePwd\",\"values\":[\"IgBAAHkAACYAIgQABSACUAOQAzAHYAIgA=\"]},{\"type\":\"description\",\"values\":[\"Checking the account options\"]},{\"type\":\"objectClass\",\"values\":[\"top\",\"person\",\"organizationalP",\"coerson\",\"user\"]}],\"controls\":[]}","time":"2023-07-31T15:08:54.122Z","v":0}
```

**Comment by jsumners** [comment]
You can see that the error originates in the `onMessage` handler. That shows the error came from the server. You will need to send an LDAP message the server is willing to handle.
