### ISSUE TITLE
Add/Delete group member not working on Windows Active Directory if groupname includes non ascii

### ISSUE THREAD

**Issue by jimmyengman** [ldapjs/node-ldapjs#939]
If I start test ldap in docker as described in https://github.com/ldapjs/docker-test-openldap and create a group with non ascii characters cn=möte,ou=people,dc=planetexpress,dc=com, I can add and delete users with this code. 

```
const mod: ldap.Attribute = { type: 'member', values: ['cn=Turanga Leela,ou=people,dc=planetexpress,dc=com'] }
const change = new ldap.Change({
  operation: 'add',
  modification: mod
});

// const mod: ldap.Attribute = { type: 'member', values: ['cn=Turanga Leela,ou=people,dc=planetexpress,dc=com'] }
// const change = new ldap.Change({
//   operation: 'delete',
//   modification: mod
// });

client.modify('cn=möte,ou=people,dc=planetexpress,dc=com', change, (err) => {
  console.log("Finnished", err)
});
```

If I try the same code against Microsoft Active Directory (Server 2019, objectversion 88) it works fine if the group name has only non ascii characters. 

If the group name has ascii characters like "ö" in "möte" (cn=möte,ou=people,dc=planetexpress,dc=com) I get error message below:
```
[err: module.exports.<computed> {lde_message: 'No Such Object', lde_dn: 'OU=people,DC=planetexpress,DC=com', stack: 'NoSuchObjectError: No Such Object
    at mess…ad (node:internal/stream_base_commons:190:23)'}](url)
```

**Comment by jsumners** [comment]
You stated in your report that the modify request works with a standard LDAP server implementation, but fails to work with a non-standard LDAP server implementation. Please consult with the maintainers of the non-standard LDAP server implementation about why their server does not follow the specifications.

**Comment by jimmyengman** [comment]
But it is strange, if I use ldapjs 2.3.3 with this code it works great with Microsoft Active Directory (Server 2019 objectversion 88) to add and delete members even if the groupname includes non ascii characters.

```
const mod: ldap.Attribute = { 'member', ['cn=Turanga Leela,ou=people,dc=planetexpress,dc=com'] }
const change = new ldap.Change({
  operation: 'add',
  modification: mod
});

// const mod: ldap.Attribute = {'member', ['cn=Turanga Leela,ou=people,dc=planetexpress,dc=com'] }
// const change = new ldap.Change({
//   operation: 'delete',
//   modification: mod
// });

client.modify('cn=möte,ou=people,dc=planetexpress,dc=com', change, (err) => {
  console.log("Finnished", err)
});
```
If I try to run the same code with ldapjs 3.0.5 it fails with error "modification must be an Attribute". 

If I change the code to 

const mod: ldap.Attribute = { **type :** 'member', **values :** ['cn=Turanga Leela,ou=people,dc=planetexpress,dc=com'] }

```
const mod: ldap.Attribute = { type : 'member', values : ['cn=Turanga Leela,ou=people,dc=planetexpress,dc=com'] }
const change = new ldap.Change({
  operation: 'add',
  modification: mod
});

// const mod: ldap.Attribute = { type : 'member', values : ['cn=Turanga Leela,ou=people,dc=planetexpress,dc=com'] }
// const change = new ldap.Change({
//   operation: 'delete',
//   modification: mod
// });

client.modify('cn=möte,ou=people,dc=planetexpress,dc=com', change, (err) => {
  console.log("Finnished", err)
});
```
I am back to the error that the object is not found **if** the groupname includes an non ascii character.
