### ISSUE TITLE
Open ssl issue with node 18

### ISSUE THREAD

**Issue by vikhil1999** [ldapjs/node-ldapjs#965]
Unable to authenticate using ldap with node 18 due to open ssl issue. 

Below is the error logs that i get when using ldap

[Error: 806096F401000000:error:0A000152:SSL routines:final renegotiate unsafe legacy renegotiation disabled:../deps/openssl/openssl/ssl/statem/extensions.c:922:
]{
library: 'SSL routines',
reason: 'unsafe legacy renegotiation disabled',
code: 'ERR SSL UNSAFE_LEGACY_RENEGOTIATION DISABLED
}
msg":"error while validating user Error: 806096F401000000:error:0A000152:SSL routines final renegotiate:unsafe legacy renegotiation disabled:../deps/openssl/openssl/ssi/statem/extensions.c:922:\n")

Can someone pls let me know do i need to add anything to my tlsOptions.

**Comment by jsumners** [comment]
I think there is sufficient information in that error to learn about it through consulting a search engine. https://duckduckgo.com/?q=806096F401000000%3Aerror%3A0A000152%3ASSL

The knowledge gained there can be combined with the Node.js docs https://nodejs.org/dist/latest-v20.x/docs/api/tls.html#tlsconnectoptions-callback
