### ISSUE TITLE
AttributeFilter not implemented on Server?

### ISSUE THREAD

**Issue by mgx0** [ldapjs/node-ldapjs#972]
Hi there,

about version 3.0.7:

i'm trying to write a mock ldap server that provides data from another source via LDAP protocol. I can use ldapsearch, gives back all users fine. Problem comes when I want to use LDAP filter. I cannot find any implementation on AttributeFilter, see example below.

```js
server.search('ou=users,dc=example,dc=com', (req, res, next) => {
    const filter = req.filter;
    const entries = users.filter(entry => **ldap.AttributeFilter.present(filter, entry))**;

    entries.forEach(entry => {
        const obj = {
            dn: entry.dn,
            attributes: {
                cn: entry.cn,
                sn: entry.sn,
                mail: entry.mail,
                objectclass: ['person']
            }
        };
        res.send(obj);
    });

    res.end();
    return next();
});
```

am I missing something, or is it really not implemented?

does anybody have any suggestion to implement such filtering?

**Comment by mgx0** [comment]
most probably the Fiters API http://ldapjs.org/filters.html is the solution

**Comment by jsumners** [comment]
Filters are exported as `require('ldapjs').filters` via:

https://github.com/ldapjs/node-ldapjs/blob/b86c493e7bbec6ae1d639951158645e1515467d7/lib/index.js#L51

Which is nothing more than a backward compatible export of https://github.com/ldapjs/filter

**Comment by mgx0** [comment]
> Filters are exported as `require('ldapjs').filters` via:
> 
> https://github.com/ldapjs/node-ldapjs/blob/b86c493e7bbec6ae1d639951158645e1515467d7/lib/index.js#L51
> 
> Which is nothing more than a backward compatible export of https://github.com/ldapjs/filter

thanks a lot, this is it!
