### ISSUE TITLE
What is Naming Violation Error

### ISSUE THREAD

**Issue by ibaraki-douji** [ldapjs/node-ldapjs#973]
I tried to use it as a client for LLDAP and i have a NamingViolation when trying to bind a user. What does it means ? and do you have any docs for that ??

**Comment by jsumners** [comment]
Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) (MRE). Doing so will help us diagnose your issue. It should be the bare minimum code needed to trigger the issue, and easily runnable without any changes or extra code. Please review the [integration tests](https://github.com/ldapjs/node-ldapjs/tree/bec2ff8e7399155ebdcbf86eec2077a792b8510b/test-integration/client), e.g. [issue-940.test.js](https://github.com/ldapjs/node-ldapjs/blob/bec2ff8e7399155ebdcbf86eec2077a792b8510b/test-integration/client/issue-940.test.js), for examples of good MREs.

You may use a GitHub repository to host the code if it is too much to fit in a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) (or two).
